; generated by PrusaSlicer 2.7.1+win64 on 2024-02-05 at 16:43:36 UTC
; Postprocessed by [ArcWelder](https://github.com/FormerLurker/ArcWelderLib)
; Copyright(C) 2021 - Brad Hochgesang
; Version: 1.2.0, Branch: HEAD, BuildDate: 2021-11-21T20:25:43Z
; resolution=0.05mm
; path_tolerance=5.0%
; max_radius=9999.00mm
; default_xyz_precision=3
; default_e_precision=5
; extrusion_rate_variance_percent=5.0%




; thumbnail begin 230x110 8420
; iVBORw0KGgoAAAANSUhEUgAAAOYAAABuCAYAAAAziW8OAAAYcklEQVR4Ae1dXWyWx5We60h7tb3Yva
; r2R7vKxV6sqtVerLKbbtXQn1RpFKEKNW2apGkoqG5oLUqdOpAS1cWCGhEI2CUm/FgGNzYE0zomUAiU
; kJRAob9xEI2l0MaqLNWqIiE1FzQP9Kij0fydM2fM99nvxVGc5Pu+eec5M2fOe55zzpg777zzeq488s
; gjM9u3b//pypUrrz7wwAOzzz777CurVq2a5vxGSpYtWzaHMdasWXMFf2/evPn8E088MaU5xl133fXe
; U0899ave3t5L991337v4G+Pcfffd1zTHwBzwu8AKOAEv/K05F+iCdAL97N279xT+rqkT+ltzDNLDfO
; kEY+Bv6ARz0hyDdAJ94G+JTowEwOeff/7Y0NDQSe1FZk9u586drxw8ePCo9gKwpbu7+80jR45MQFG1
; xoBCJiYmfghFaS4yVycvvdT1syNHvjSluchcnezevfv06OjosVo6wRh9fX0XDh8+PImNWWMMVycYs8
; YY0APGwKaEfrjfN5wPYwBMpqur6zKUg7+1NyeAgtWkk4ZOA20AyVrit+lU1h7DtpZ0GmhvTuhkfPw/
; 5y5dMtchR4/+9+xDDy1V3Zx4ZmAEsU9ozTEg0AHGWL58+Tt0KtfSCU6zWjrBpsTaon1Ca5nzGyb3g+
; SKYUL2A2gCSK6Y7R7bbqcGgFjIrnvsup2lY9Azu66Y9qJet27ZzLlzH7hGm5Lk1Vc/+O53vvPROU2d
; 2M9su51aOnHdY9ft1NAJGXyfTux1XSI+95heyTgHjMkBjaylTwlaAJK1DP2GBoC2tfT9fwmAvt+AYk
; LuHuGJRSIdA78xPPx/s+6GtOXChdveGxr6+MzSpR8Tb5yYTkjvpTrxGXwXz1KvyWfwfTop8Zp8Bt/F
; y36HTv2eyZlQjoWXAuizljmT54wRspYaANqSG0ywFzX3hF616jOzOBFjm9KWEyf+5V18p5ZOSO9cna
; QMfkgn3BM6ZfBdnUi8ppTBdz+b4zWZ0EPmTqgEwJS11AAwZS1LAaRFRouTMwbnVQD/f9u2JbO5G9I9
; PQcHPzKboxMyLpzFaeskJ/gkjVRyvCaOcXF1kus1cQy++2wpr8loTYgDoG0tS1zGFIAS48IFkGMtQ8
; pNPef999/zLoI6kk3pnp7Ll392VjrXHJ3EvCapwfc9Jw6A0HOWUlM5XpPU4NtjxLwmY09OYi25AEqt
; JQdADeOSAlBqLUNic8Q2XqEAj1Rwem7c+MnZ+dCJjct86ETD4NsS8ppKjYstIa/JAEBMLmWFSgHEwt
; OcUAjAWkS+DSDC+SXWMiR2tBPPf+jQ/8xqbUhXRkb+aw6nZw0i39WJpsF3dYJnhx46OjrerpFcYXsS
; tZIrbE8CY2AsA0IXJDv+RXMwV0kYoyahi40/OTl5REro5gJ44MCBH4+MjBzXCq/7xtiz5/FfXLz4b3
; +stSltWqW//2tTNXUCkh2bslZyBX4XCS/79+8/UVMng4ODZ2onvPT09PwCeGGDGgqilL5fhISspU3o
; 1jgxsSFhNWslPtiuWMjt1FkAH5mtvSF9gaF77vn/akT+fOikVuKDfWJSwkuNxAc6MWmfGHtRaAIYe8
; fUAjAUTNBOfPC5x9okO9zK06c/NK+b0g0MgVbR0InPPSa3U0snPvfY3kQaOvG9e2sEsNx94kuuMO4H
; NQBMRSo1AEwFEzQjgCFPQotk37Bh6QxOrlu1Ke3T8/vf/9RMaXJF6N27hCN2dRIj8ksPmJy1o+E1xe
; IhJvZgXABD1lIbQE5VgBRATqSyhGSvGeCRiiTflnSZs15snXDG4FBTUq+Jm/Ai8ZpEPKYUwJS11AAw
; ZS01ALStJQdsbuJDV9d9s5o0iLbk5ttKkyvwPegjVyeS6DHXa+IYfFfvuV5TrsE3GgCW5srmAKhB5K
; cA1ODaUiQ7xkAOa6tuSNe1jeXbauokZMykBt+WlNckNfjuc8bSRbkG35QAqEkahwCUWksugBJrGcPL
; d0J3dDw4c+bM7XPtsCltcQND2skVIa9Js7ok5DWVGhffPnG9Jsk+MVIAMSFunisXQPx2jS4JNoCgWE
; qtZUgoAo3n7+v7cNttSPf0BK1CyRXatIR9oti0RA29k/GvlVxhe01Sg2+4g2ISY2NjL9XuYDAwMHAW
; 1fLam9IWKAaEbg3+lgTG5ezZj77dTpswJjjxcfLX0glIdkp4qaUTrKn56GAwPj7+IoyYZOMb7iIja1
; mru4B97Kf8dqnY7rE2H2mLdp5rK52eWoXYtk7IPYbea+nEroLhBOs4YrvHUt7e5H7QF5wBaJoA+txj
; brQzJaFggmbiQ04h80IQ5NuWFGKT+Op+oXfoqJQjtnXic481iuPtZ/a5x5LKHSOdkCaA+I1U0awGgK
; lgggRAVzo7PzXHKWRudzl16h+uYc5SvFLReA2vKVX3GwrWcSQnuYLD25ucCeX8kBRATpcEKYCcqJg0
; 8QHf27HjjrYO8EiFU4hdohOu15Rj8G2Rek2c6HEub29CoElODi6A0pQ5DoCSLgkcACHIkjl27D8W5a
; a0BbTKypX3zuXqhPtqwvGaOAZfuvaldGEOb298i740HJ4CUIP/TAFot1yUuic5ALZKnmuriK8QO1dn
; uTpJeU2lOdI5XpPU4NsSy6wztYj8EICahcwhALU7kvsAbNU811YRBIbsfFsNg2+Lz2vSTnjxeU0aBt
; +WECtgqAI81nJRA8DOzs63Sq1lDoC1uiTYAHZ3L/3DYgrwSAWBIeQE1yLy7RMY66tGlwTba1qxYsXv
; aiVX0AGDeeCfZtOmTRfRkr5GJ3IS/DZVstckdEFM1+xggDGOH39oqp02x60WuLYTE/df0aBVQjqhhJ
; daHQwgO3bseG0+OhjQlR2GNmSN7gIukV9aJxcSu2hWWlKUEhQyt2Oea6uIViG2LbZ7rF0cT2K7x7WS
; UewmYrRPjDtRrUUd6kiuCWAomKAJIH633fNcW0VKC7Ftnfjc45xgHUd8XRK0iuNJQvEQk7vYJRMKJe
; 5qAJgKJmgA6F7Y04iOgFqSXnwUMvjuYi9JF83ZA9Li+Nw9YFKLmuN2cotmJQByo8dSABdqnmuriOTi
; I06lhtRr4kSPbd6eUz2SEz02OYs6x+2U1rVxAJQWzXIAXCx5rq0gcG2BdSowJO2SwPGaSuhCzr09Pv
; eYvTHpgVO3PpUWzeYASBMqeXdIAbjY8lxbRRAYCuXbahQyp7wmjS4JqcSHnKsdWBuTxOd2lt7fkAOg
; 1FpyAFzMea6tIm6+rYbBd/XuSxflNBHLEV8AVZJcYTiD2m5nLSLfBhBXsWu1fQgB2N392FsaF/Y0oi
; M4Pbu7H75a4woKCBn/1atXX9E0+O4+wfpFjoDUPTaSiYEE3bVr109qtqQHoYsOBtq8lC19fcvfunjx
; HxvXtcUEp+eWLffO1NI7NjzWcM2rG3AqI6kGBkbC2xvuhOjFtTRcHBKb18lJWJZIk+faHuLm25aK6x
; 5r8va22O6xlLc3uQvZx+uE/HaphNxjTQCbAE97SWkhts/g56xtiYTiIRLe3qQ+kPPiygkXxyYU43VK
; AcR35vvCnkZ0pPTio9SmkPL2vn0Se73jpIua2ELmNKiVup2cMjApgLf6wp5GdISbb8stA5O4ndzocW
; 4HeqMxIddy5FiFkhOQA2BTyLywJDffVlr3y3E7pXW/OQeMcf+DtEEtZ9NpFM2mAGwCPAtbQhcfab0z
; ptxODbowdsAYOk417m9IWQXtLgkhAFv9wp5GdMTNt9XukuBLF9XukmAHUGmT478ZDLJ27do3ahH5ZB
; XWrVv3m1pdEghAXFvfLhf2NKIjN/Nt736np6drStPg+w6Y9evX/7pGlwQINVCnvWiwmHGHPSZVs4MB
; qr9rZAqRdHY+evX8+X9t0uoWqaCIXbsQ2zb8g4ODZ2onvKCDwfDw8MkbHQzwkqwRLg5NyHaPa3QXwL
; Nv27akeZdsRNTfNiW2e+xzO7X2if2uibGM/QHN7gIhXkezuwCet8lzbcQV0CqlGUOxeEgpb29LKHps
; fA9UEnHKCfBonNBNIXMjMSm5+CinS0JpumgqemxCX5S4ndhknKoAyQndFDI3whHuxUdcupB4e07gNC
; d6bFKbINcqSE9Zjt/e5Lk2IpGcfNsSutD+bmwMDl1ocjdOyCpo8Toxv73Jc22kVGKBIY0uCamCjhz3
; mLUx3Y1jWwWN+xt8FsU+oZs810Y0xb74SLtLAu0T994eSTadkVgFFDFjk9YgdMmC4fe3b394uslzbU
; Rbbp6en36nVpcEOmC2bNlyXtolwUg2DYhWdDDQCBf7hAjdZ5756huTk03ktRFdOXbstve576//WquO
; OLRPqEuChLc3HCtgB3hqdReweR2MsXr1V6ZHR++Yef319lJ+I60pY2N3zNB7HrmdlGSjsX5d91iaVG
; 9yT7BQgEcSLg6NEZoAABwYWDZ98mTj1jYikxMnzPVnnvnCFfeE1Ly3J9Q1UsLbm9QHchrUcntm+jZ3
; itfB765f/8j05OSHZpvTsxGOHDr0wfdpv9VRKqO0fU0OXcjh7Y3WZpNYBUmW0YoVD84899yHZ157rT
; k9G4nLuXPm+p49907nbjbba8t9PePShblr3sROMIl7muu3l/Cf+O73vrf8yo9+1CQbNOIXrI2enq9N
; SRNecg6YktvRU/f2GPehNAqZU367RpcECgzh9Gxc20Zs+cEPllzVSnjxuZ1aXRJimXWGdrvG/Q0xq2
; BPSLP7NZ5769aOqePHG1plscupU7e9hwBPicF3jb/rdmp3SfBl1mGsGx0MkDBQq4iZNuPWrVvP1eqS
; gMk9+WTn+67t/77TnJ6LU8bG/n3uG9/48rT22qIDpr+//9WNGzderLVP6BUQ+wQHpMGANTcmNg0qs7
; EptQuxbYHVQSeGwcGl02fONIGhxSKgQXbv/vxlrONa3QUo4WXbtm0/1ebt7TGefvrp1zHOjQ4GdILV
; 6C7guseahdj2hGz3GP8OWqUJDC18AQ2CAA82SmkdcczgUzwkVdAhFdc9xljGXeQ5zWhzJ+QDSRPAUP
; TYDgw1tMrCE9AgCPD44iHU1Ko0XTQWDyG3s/TenlhTdeP7cEl3gVwapATA3OgxAASt0gSGFo4gwLNp
; 0+emY0Yda6IkXTSHLkyVeZXuExNb1Fy3ExPilIFJAORGj+n0PHy4ybdtdxkevn2us/Mr2XrHGuG4nR
; K6UNL/J4cuNKkHzekugM/hMxL+kwNgSYcygPDcc1+40gSG2k8Q4OnvXzpdkvCScjtL6MLcgg4OXWhy
; JxeyCtL7GzgAanVJaPJt208Q4Ont/davShNeYm6nVkvKWL4tN5vOcCbnWgXtKJgPQO0uCZAm37b1BQ
; GeoaElV7VZAru7gPZ1BxA3K0iaTWe4GweTAtdCvJHWhFwAwRkRp1OLN0Jg6OWX/7np3t5icvTo31/r
; 7V1+pRavjo0CY69t8O0xsDdwQkrdY8P9AgbZt2/fyyBDta95JwFYQ0NDJzFGTUIXxqW398lfHjjQ5N
; u2iqCQmTJsaiSjYC3ht2H0tXl7W7A3BgYGzkp5e8NZyO4RvWaN3jXv9oTc3ERtAF33+OaLf8cUWk60
; 0yJeSOIWMvuaWpWKGw/RvObd3ie2eyzl7U3Oh2KJu1oAxvx9LQDJWvrcY8q3bQJD8y8jI/5CZs32Na
; HNUcrb2xKLh3Az60zsf+a+uJYCuCajS0IpgLnR45ufWzrdBIbqy5kz5vrOnelC5hKvKTfAU5IuGjP4
; 7rPk7hMTe1DufZZcACUnoQRArivR5NvWFypk5nQK4K6VHINvi8Tt5NKFufm2JjYhSV1bLoAldW25AJ
; aEw5tC7HoiLWTO9ZpKX31S3QU4azAkvgbqwY1JC7m0kDkGoJTX4QLItZYxAJtCbB1Bnmt//4qp0kLm
; mNekVcgcczs1E14ogOpiYmgCGvc3pACs0SXBBbBGpK3Jty0X5Lk+/ninGu8d6nOsyXv73E4tg+/bJ3
; TA3Li4FlwhXS9dgy8kAIlsrUUaA7ADBw78WLPtgw/A/fsffePs2b/7czttilspoEH27v3iVA0iH4Lf
; 3b179+k9e/acrpnwAt4T+0TaojVnDaOhAPbIjUJpEPkgdGt1F6Bjn8aoca0CWUsidGslPkDxuBpi48
; aOyy++ePtcc3rGBXmufX1P/ly7ON7VCRJetOqIfYI1i32yYcOGn9dKfKB9gs2Jfxo6wWp0F3DdY064
; OFdc97hG4oOvx26TbxsWynO1daKdV+3GQ3KjnRzxucea17yTuO7xjWZc7oNoABi73kwTQPod37NqAR
; h796Z82+bio78JsqdCea450c5SnaSinbkSi4doJT74DD6J8X2hBMDQ/Q2aAOZGj0sA5CRXIDB08OCS
; q4vdtbUv7InprkQnOfdZlnpNMYNvS0niQyrYajQB5J62EgAl0WMugJLo8WLOtw1d2JPSO8dryjX4rk
; 44B4yELuSyALkG32gAWMrr5ACYay1LAVxTUDSL31279suLqhA758KemN5zuguUvF7lek0ldCHtkxSN
; wjH4phTAkvsbcgHU6pIQA1AruQLy8MOfnV3o+bbcC3tSOvF5TZqFzCGvqdTgu/skFEDlGnwjBbAGke
; 8DsEavUBdAbhOxHMHzfve7Dy7IfFtunitHJ+Q1aRl8Vyf2mtUy+O4+sdes1LgYCYDoeA5ep8b99QTg
; zp07XwGhq3nPiQvgunXrfnPw4MGjAK5WcgUCQ4cO3fvbheLajo5+4u2aOunr67uARBFtg2+PseavXf
; tzAjxSwabHGFKDb7iTglKQLVTjmncSbHgQ+dg4tRIfyFrSGDWyhchadnd3v9nu+bZ0YQ/wqkWy03se
; key1dVIr8YHcY1w9Ik18MJwJuWVg2t0FfO5xjcQH1z2ukfjgusd/Oz3bLzCEQmb7wh5tkt12/wj/Gq
; 9KrntcI/HBdY+ldcQm50OxMjAtAGNVAVoAxvx9KYC+34kFE/Db7XLxEWiQXbvuv+JzxTRJ9lDdr5ZO
; UmtU696e2BrlHjAmZ0I5RL4UwFxepxTA3GBCyQmdG0zAPFu9ENu+sCc2lxKvKbfut0QnuWVgJV5Tbo
; DHDqCmDhiTmhDnxZULoKRLAhdAyYnOAZBEklzx2GOPXm21fFs3zzVXJxyMcw2+ixcHY47Bd/XOOWAk
; 0eOcVwGjMSEJgLnWsgTA0qLZHAA1kita5eIjZC319MQv7NHSiZSayvGaJAbfp/fYAVP6Cpd6FTD2vw
; BQrULmEIASa8kFsNS45AKomVxxqwuxORf23GqdxLymEoPv6iTkNWl1SaDf8mXWGQKwBpHvAlijS4IL
; YKm1zAGwVnIFnn1gYNm8BoZKLuyJ6cReT5oG39U7ndCaBt/VCR0wdDuddlMB+9kpucKg+PPw4cOTWG
; SaE7IB7OrquowxahH5BODY2NhL2tkiLoCjo6PHRkZGjtdKrrhJsq968/TpO35f+/QcH/+nP23e/O1L
; tXSCzf7CCy9M1upcQXpHksj+/ftP1OpcAZ1s2bLlPMbBxqw1Bvhb7JMbHQwAGjZOLUKXIpVE6NboLk
; AWB+R3rcQHcsWQXAG8apHs5IqtXbv6cq3AEOW5dnZ2vlWLZLeJ/Jo6we9CJyXFB7k6wdr1uZ0aQt4k
; dHJjY9qErjaArntsu52l7wDuhGywQn67VHzusXYLf597XKMQe3z8A9dAg9g60X6NcTuSaxbHk/jKwL
; QTH3yFDa7bWTqG790b/824H9IAMBWp1AAwReRrARgLJtiBoZJFnUquQGBI4+Kj4eFwIbMGyU6Yh3Si
; 1V0gZki0Eh9i8ZBYRQxHYvEQE/qCFMDcSGUJgLlFsyUA+qxlTImSRc2JVJYUYucWMpd4TbmRyhKviU
; NNSb2mlMF3dSL1mlLRY6MFoG0tOQ/JBVDidhGA2Mg5zyaJHnMjtZLoMX6Xe/FR6MKelN5zdSJ1hble
; k4SaivXU8YmkSwLXa8o1+EYDwFJeJwfAUiI/B0COtQx9P4dkJ2spdX/p4qMYrUJ5rqXJFTGvSVMnIb
; ylBp+rk9L37ByviWPwTQmAmoGDGICaRbMhACXWMiQhkp3jHqckdvFRbp5rrk58rwKaHclDOtEk8kNe
; U6lxcXVCXpO7T7gG30gB1JxQCED6W5vIdwGskVzhGq1ayRV08dGFC7e9BxoEF/Zoc6y210Q60e5IPl
; 86sb2mGl0S3ANGavCNBECQoOhgUKvtPSaHtvcgdGtWyxOhWyu5AoLFPDEx8cPaJPuhQxte3bfvm5e0
; aKiQTpBgUTO5Yj50Ah4aOsHm0TQurk5I7xKdGM6HbSJf05VxlUPWkixPjcQHspYdHR1v1yLZyVpiId
; Qi2clzIZ3USHywo8fArZZOaE1BJ6R/bZ24RH5NnUDv0pP/L2jlsBKXZzcvAAAAAElFTkSuQmCC
; thumbnail end

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M104 S215 ; set extruder temp
M109 S215 ; wait for extruder temp
G28                                        ; move X/Y/Z to min endstops
G1 Z0.28                                   ; lift nozzle a bit 
G92 E0 
G1 Y3 F2400                                    ; zero the extruded length 
G1 X180  E40 F500                       ; Extrude 25mm of filament in a 5cm line. 
G92 E0                                     ; zero the extruded length again 
G1 E-0.2 F3000                                ; Retract a little 
G1 X181 F4000                              ; Quickly wipe away from the filament line
M117
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
M107
;LAYER_CHANGE
;Z:0.25
;HEIGHT:0.25
; BEFORE_LAYER_CHANGE 0 @ 0.25mm
G1 Z.25 F9000
; AFTER_LAYER_CHANGE 0 @ 0.25mm
G1 E-2.5 F4800
G92 E0
G1 X139.75 Y139.75 F9000
G1 E2.5 F4800
M204 S5000
;TYPE:External perimeter
;WIDTH:0.499999
G1 X80.25 Y139.75 E5.20515
G1 X80.25 Y80.25 E7.9103
G1 X139.75 Y80.25 E10.61545
G1 X139.75 Y110 E11.96803
G1 X139.75 Y139.69 E13.31788
M204 S20000
;WIPE_START
G1 F7200
G1 X139.75 Y139.75 E13.27988
G1 X135.863 Y139.75 E10.81788
;WIPE_END
G92 E0
G1 X133.837 Y80.61 F9000
G1 E2.5 F4800
M204 S5000
;TYPE:Internal infill
;WIDTH:0.5
G1 X138.18 Y80.61 E2.69745
G1 X139.39 Y81.82 E2.77525
G1 X139.39 Y80.61 E2.83026
G1 X80.61 Y139.39 E6.60963
G1 X80.61 Y138.18 E6.66464
G1 X81.82 Y139.39 E6.74244
G1 X86.367 Y139.39 E6.94917
G1 X139.39 Y86.367 E10.35839
G1 X139.39 Y87.577 E10.4134
G1 X132.423 Y80.61 E10.86136
G1 X133.633 Y80.61 E10.91637
G1 X80.61 Y133.633 E14.32559
G1 X80.61 Y132.423 E14.3806
G1 X87.577 Y139.39 E14.82856
G1 X92.124 Y139.39 E15.03529
G1 X139.39 Y92.124 E18.07435
G1 X139.39 Y93.334 E18.12936
G1 X126.666 Y80.61 E18.94747
G1 X127.876 Y80.61 E19.00248
G1 X80.61 Y127.876 E22.04154
G1 X80.61 Y126.666 E22.09655
G1 X93.334 Y139.39 E22.91466
G1 X97.881 Y139.39 E23.12139
G1 X139.39 Y97.881 E25.79029
G1 X139.39 Y99.091 E25.8453
G1 X120.909 Y80.61 E27.03357
G1 X122.119 Y80.61 E27.08858
G1 X80.61 Y122.119 E29.75748
G1 X80.61 Y120.909 E29.81249
G1 X99.091 Y139.39 E31.00076
G1 X103.638 Y139.39 E31.20749
G1 X139.39 Y103.638 E33.50623
G1 X139.39 Y104.848 E33.56124
G1 X115.152 Y80.61 E35.11967
G1 X116.362 Y80.61 E35.17468
G1 X80.61 Y116.362 E37.47342
G1 X80.61 Y115.152 E37.52843
G1 X104.848 Y139.39 E39.08686
G1 X109.395 Y139.39 E39.29359
G1 X139.39 Y109.395 E41.22218
G1 X139.39 Y110.605 E41.27719
G1 X109.395 Y80.61 E43.20578
G1 X110.605 Y80.61 E43.26079
G1 X80.61 Y110.605 E45.18938
G1 X80.61 Y109.395 E45.24439
G1 X110.605 Y139.39 E47.17298
G1 X115.152 Y139.39 E47.37971
G1 X139.39 Y115.152 E48.93814
G1 X139.39 Y116.362 E48.99315
G1 X103.638 Y80.61 E51.29189
G1 X104.848 Y80.61 E51.3469
G1 X80.61 Y104.848 E52.90533
G1 X80.61 Y103.638 E52.96034
G1 X116.362 Y139.39 E55.25908
G1 X120.909 Y139.39 E55.46581
G1 X139.39 Y120.909 E56.65408
G1 X139.39 Y122.119 E56.70909
G1 X97.881 Y80.61 E59.37799
G1 X99.091 Y80.61 E59.433
G1 X80.61 Y99.091 E60.62127
G1 X80.61 Y97.881 E60.67628
G1 X122.119 Y139.39 E63.34518
G1 X126.666 Y139.39 E63.55191
G1 X139.39 Y126.666 E64.37002
G1 X139.39 Y127.876 E64.42503
G1 X92.124 Y80.61 E67.46409
G1 X93.334 Y80.61 E67.5191
G1 X80.61 Y93.334 E68.33721
G1 X80.61 Y92.124 E68.39222
G1 X127.876 Y139.39 E71.43128
G1 X132.423 Y139.39 E71.63801
G1 X139.39 Y132.423 E72.08597
G1 X139.39 Y133.633 E72.14098
G1 X86.367 Y80.61 E75.5502
G1 X87.577 Y80.61 E75.60521
G1 X80.61 Y87.577 E76.05317
G1 X80.61 Y86.367 E76.10818
G1 X133.633 Y139.39 E79.5174
G1 X138.18 Y139.39 E79.72413
G1 X139.39 Y138.18 E79.80193
G1 X139.39 Y139.39 E79.85694
G1 X80.61 Y80.61 E83.63631
G1 X80.61 Y81.82 E83.69132
G1 X81.82 Y80.61 E83.76912
G1 X86.163 Y80.61 E83.96657
M204 S20000
;WIPE_START
G1 F7200;_WIPE
G1 X82.216 Y80.61 E81.46657
;WIPE_END
G92 E0
M107
;TYPE:Custom
G1 Z2.25 F600 ; Move print head up
G1 X5 Y209 F9000 ; present print
G1 Z70.25 F600 ; Move print head further up
G1 Z150 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84; disable motors                    ; disable stepper motors
; filament used [mm] = 132.08
; filament used [cm3] = 0.32
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 1m 5s
; estimated first layer printing time (normal mode) = 1m 5s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = D:\\1111(已去底).png
; bed_shape = 0x0,220x0,220x220,0x220
; bed_temperature = 60
; before_layer_gcode = ; BEFORE_LAYER_CHANGE [layer_num] @ [layer_z]mm
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 5000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1.1
; bridge_speed = 30
; brim_separation = 0.15
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 20000
; default_filament_profile = "Anycubic PLA @MEGA0"
; default_print_profile = 0.20mm NORMAL @MEGA0
; deretract_speed = 80
; disable_fan_first_layers = 2
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = ""
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.95} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84; disable motors                    ; disable stepper motors
; external_perimeter_acceleration = 5000
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 40%
; external_perimeters_first = 1
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.98
; extrusion_width = 0.42
; fan_always_on = 1
; fan_below_layer_time = 600
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_layer_change = 0
; filament_settings_id = "Anycubic Kobra 2 Pro-PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 20%
; fill_pattern = grid
; first_layer_acceleration = 5000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.5
; first_layer_height = 0.25
; first_layer_speed = 80
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 200
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = disabled
; gcode_resolution = 0.012
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 20000
; infill_anchor = 10
; infill_anchor_max = 10
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 15%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 1%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ; AFTER_LAYER_CHANGE [layer_num] @ [layer_z]mm
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 20000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 20000
; machine_max_acceleration_travel = 3000,1250
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 5000
; machine_max_feedrate_e = 100
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 16
; machine_max_jerk_e = 20
; machine_max_jerk_x = 20
; machine_max_jerk_y = 20
; machine_max_jerk_z = 8
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.28
; max_print_height = 250
; max_print_speed = 300
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 60
; min_feature_size = 25%
; min_layer_height = 0.08
; min_print_speed = 25
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}-{layer_height}-{print_time}-{month}-{day}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 100%
; overhang_speed_1 = 50%
; overhang_speed_2 = 50%
; overhang_speed_3 = 100%
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 10000
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 120
; perimeters = 1
; physical_printer_settings_id = 
; post_process = ArcWelder.exe
; print_settings_id = Anycubic Kobra 2 Pro-PLA
; printer_model = 
; printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_ANYCUBIC\nPRINTER_MODEL_Kobra 2
; printer_settings_id = Anycubic Kobra 2 Pro-PLA
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 2.5
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 80
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 5
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 6
; small_perimeter_speed = 40%
; solid_infill_acceleration = 10000
; solid_infill_below_area = 15
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80%
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM104 S[first_layer_temperature] ; set extruder temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28                                        ; move X/Y/Z to min endstops\nG1 Z0.28                                   ; lift nozzle a bit \nG92 E0 \nG1 Y3 F2400                                    ; zero the extruded length \nG1 X180  E40 F500                       ; Extrude 25mm of filament in a 5cm line. \nG92 E0                                     ; zero the extruded length again \nG1 E-0.2 F3000                                ; Retract a little \nG1 X181 F4000                              ; Quickly wipe away from the filament line\nM117
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 1
; support_material_closing_radius = 2
; support_material_contact_distance = 0.28
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 80
; support_material_style = organic
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 1
; thumbnails = 230x110/PNG
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.42
; top_solid_infill_acceleration = 5000
; top_solid_infill_speed = 65%
; top_solid_layers = 0
; top_solid_min_thickness = 0.6
; travel_acceleration = 20000
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
