; generated by PrusaSlicer 2.7.4+win64 on 2024-04-27 at 17:10:24 UTC
; Postprocessed by [ArcWelder](https://github.com/FormerLurker/ArcWelderLib)
; Copyright(C) 2021 - Brad Hochgesang
; Version: 1.2.0, Branch: HEAD, BuildDate: 2021-11-21T20:25:43Z
; resolution=0.05mm
; path_tolerance=5.0%
; max_radius=9999.00mm
; default_xyz_precision=3
; default_e_precision=5
; extrusion_rate_variance_percent=5.0%




; thumbnail begin 230x110 7736
; iVBORw0KGgoAAAANSUhEUgAAAOYAAABuCAYAAAAziW8OAAAWb0lEQVR4Ae1dTYyeVRW+CxZqWBCDSR
; eNEnXBggWJLow/sYkGQ4SQQDQ2GAlRwsSGptWmqaMgEcxQ0g5gqZ2W0knTltqhf0ChAgOt/Mmf2EKq
; QULAQIILFiyadNHF2GfMNZfL/TnnnnPe7/tm3sWTNp3Oe+97z73nPO+5zz3XLVu2bC6FFStWvL9ly5
; aX8ec111xzGn9ft27d27n/r4Xly5d/5NtCu3ffffffgCuuuOKMZbt4/u23337qzjvvPIm/o330A32w
; bPeyyy4769u67rrrPsR479q16xn8adkucMMNN/xnkDa+5ZZb3vTj3oWNMdaxje+///4XMO7W7YY2xr
; jXbOxKD4SxHn744cf37Nlz3Lrz8YtMTU29hLZhvC7bvfXWW/955MiRo5goXbULYHzRLiZKizO46aZL
; 5tauvZjdLtrCJJmZmXmqC2cQjvX69etfh42xWLpqFxgfH38LY42Fgn501S4c0tGjRx+FjfH30v91JY
; NhcmKihqu9ixfAYkTbq1evftd79C4G0EerlStXvof20Y8u2oWRYCyMs/fonMV5331L5k6edPPA3y+/
; /Juk3/M23rhx4wlM1i5tjHdF22NjYx8MwsZr1qx5B+1jrLto1zMSjLOf3yUbu1LnEXLDyeOpjtWLpO
; gU/i2kHxbt4n3w/JBOefqBf7OcrJ5OhR40/Iwo/e6113517tixT/1/UXo89tj58xF0GWGChm0MysYx
; xbSycUyZY4pp0S6AABNTZvy95JBcrfPxzymrXTJBUwMUDmDoLDRQ4/uYrHhfbY/uo1WOqvuf5ybrHX
; dc9IkFGeLFF8+b++1vv/yJ6FmzYeiQtG3sJ2jOhlSHxIVnJGg/93MLhxTaMPXcOK8R/sxROx9PZq0B
; rHU+NYBaFJPqZLQ9eoqR5NqNPfrVV39tPiKWFmWIAwcumP8dP9bUBI8faw2HhDGjJvE484ECahJPO+
; hQk3ho13+yhfPB+c5zO6RBMVsykBoUszUDKfXoKcpMgV8kmzd/70Pqgoyj59TUtz6iJB3i/kptTMlA
; 5mwsoZjextzkYRh0WhxDjXWWbBzmNZwkRd46gK2dT01W7gCm+D7X4C0e3U9QCiNJYefOz59tWZRx9K
; QmhkJ4h8T9jJBGoFaKSWUkJRu3OKQwidfSbhh0nMY3G2cAOZSZ8iLUAdSkSFyHJJmguQRPKxA9a4mh
; 0vhhvGvjp7knyqGYrYykZmPKGkkl8VqBZzjpQ+IXKQ2g1aZ9jWJabdrXHJJ0gv7hD0vVFmQMPJsbPS
; kOyWrTvpbXaKHMHBvn8hq1JF4rnObDwhcJKWYr3+cgFRE1KHMNOY8uocyIkpwETyvQBtpqsbHfZw5t
; bL0vmKOYVjsFoY1TeQ0pZS7BWb2IH0Bs1lt1PjeAcAJ+YXQhMQO8R1+7du3bkgmKLQ7rBRlT29S2Cs
; fGq1at+ndXMsLQxphbXckIAR90MLe0KHMOzuolMIDT09PPQeql8T3JAZQsXs5n5b1TQHteVsc1GBbG
; 7t0Xdroo48SQ31bh2BjveuDAgdmuFofHxMTEGxhryjevJuB8vKzOUtvrLB4a8v2Qg1sPYNyWNcXxCN
; uCV+WKIX72s0vnI9egFmUYPal62zCJVxNDWNg4FKJ3YWMgnE9WYggPZ9n5cOJay9tyfF9TDJGbKCk6
; RRVDWCZ4WlHT2/oET8rGlvK2XBJPUwzBsbHld7Wz7nw8gHHSQApKitxKb1tLkZcckvY2iDZSeltKEs
; 9C3kZJ4lnpbWtJPCuH5DQoJicDGQ6glH5wNu01B5CbIo89etcJHgm19YkhTgZS8zOCu2nfKobI2Rig
; rA9Nh4RnOAnFlIRyKUdvNbx0AFtT5GhrYmL8zWPHvnR6FBZlCPT5j3/8zSluJJLK21o37aV5jdZ9b6
; lDClmn85OVe4JCY9O+JWmgoSppOUEh3RNFUmWUFmMuerbYmEsxNTbtW/IaWpG+Ja8Rn7xx8cSrDaD2
; pj2HYkp1rjGoSQOpjDA8yDzqaNHbcuRt2pv21KCjKSP0z6Oup9TJG5camNxqR2NWm/Ylisnl+9xJUx
; pASTp+2BM8kujZoreNT1DEdrDatK/lNTR1rnG7paBTkhG61ANT345WnY9fJKYSVjrXGHHSQOpBaweZ
; FwIketuQYkpP3nBt7OeSlc41Riro1Cizqw3gjh07nrfWucaAobZu3frihg0bTnS1eRwaanJy8u+lk/
; YldKVzHRZI9baDsvG99977SldS0XA9ocgcxeG70g/hWSC3wiLR3JeiDB4cwubNm1/uQk0SDt6mTZte
; 3blz57MtmepR2QbRRktiCDbGvMJE7drGkPNhUVqKIVIAI9i7d+9xSl7D5TofJni6lLeFx4Y4SQMpYr
; 7PyVQPWuc6LKDqbeMknrW8zSNO4nVRfAyIPw0piVaXm6Apvm8pbwsP4qYG1FJvm3M6FDHEsOhchwWl
; xFApiWd9bCyXxLMOOqUcSUkM4SgTNB5AbekTJUVuobelJnhyHn0Yda7DgjgxREniWcjbqDaWiiFS70
; LZVsyJIRyn86kBlFDMlj1RLcEyd0809OhjY8vOLKYETyswRtdf/3V2RNKimJgjnCSeVtDhyghTQcfV
; an1SBrCFYko27aliiNoC4/YZ///BB696f5QWx6Dx2mufmR+zlm2VVoop2ROVBh3JtmKY13DSTftwtV
; M7o3WGjps0kOyJYmIhuTFKi2KY0HIQG+DmNbRq/3DzGlrlc3zQcZKHxC9So5jasif/zFoEXOw612EB
; 5yB2bGMKQ9JO4lDzGha1f5zWg8IFkBpALt9vGcBU0kBa63Mh6VyHBZyLj1I2jueQhcOP51Aq6FjKCJ
; 3Fi4QU07LzuQH0SQMJ31+oOtdhAeXio5KNPcXUPtiQQxx0rGWEzupF4MVQiAvKoS6LcWEA/b2LcAYt
; z1gMOtdhgKRCH9Q73sZdKdIABJuDBw8+2XqP6cAXJjwa5G24X7MLjxYOHDyZv++RkwRYbDrXYQESQx
; y9bXjHpWWtnxjhHZeWYgiThZni+11In1KUmbMvtVh1rsMCit42lcSTbJ1xEFNmCzGE2cIs8X1L6VOJ
; 79f2pUCj+gTP8CC3rVJL4lnpbWtZf6ug4zRWO2fTXltvS13sKTFEn+AZTsR6W2oST1tvy7njUjPo4B
; mOW+untfNxwxg8Cf1oSZGH+1JTU188e/Kkm+sxvICNtm7dwDrIHGbjW4NOuNA481Mj6HjW6SgnKHKd
; l2zaSzi69MKe2dnP9otyRPDMM0vOSA5icymmdE+0VW8bnrzB7zn/Aw5Hl27ax8+icnQpVekTPKMJyb
; YKh2Jqlc/h6m1TrNNxJ75F7R9KOUmpzrU/yDz6sNLbWtX+qR3yKDkOV1rtIVXUEulSXiT85m3l+x79
; QeaFBYneNpXXsNC5ptZTfMijRpldbZHgF607HwKD5jk6HMOw3sjcY7DQ0NtaX2qcWk9YS5TklKstEs
; iP9uzZc7zLokUYQFQxO3To0BMti7LfBlkcaNXbYk7hjsuu5XxYnI888sifEeRq37wu94Nw01677EIJ
; Id9vqfXTJ3gWF7iJofge0y4KzAEh66QkWl2p82GHLWr9lDrv/416Jq4/yLy4UUsM5b7p/OeSVdDJbS
; uGxedS7TpK5+NFol1OkrInWion2R9k7gHk9La18jlhXkMz6NTK55T28l3cecq3pKTWTwy0R639kxIs
; 9zrXHjH8xUeYI6kLe3Jzq1ROkgu/4Cg0OSWGcK2b9lSKWUKrvhADOD297lSf4OmRA6LnQw+tOsXd95
; bWMG7dVowVeE5auKilnGR/YU+PrqB18RE1YEi3FX2i1WlkpDhn4iTlMvuDzD1aIL34qBZ0tMvnzEdM
; 6UNij5FLA3P4fgr9NkgPCVpvxK4FHa1ymTGc5sP8ao+/WSWd73WuPTTRqrdNBR3LO0+c9gO9l/FZKR
; TGau18r3PtYQGJ3hZz+a677nrNslym2cL0L7F79+6/4J7L1rILP/zhpXN/+lOfee2hi5mZ8859Wl3a
; NK8xl1Gdz6rWj+nCjO+4lIT87373m+e+DZbMvfrqaBm/x3Did79b0hxowk806wJzTvNhpT1RadmFa6
; +9ZO7RR3ta26MNx465uZ/8hE9fgdxZYMsCc05rtVMOMkv1tlde+bW5e+65sI+ePVjYsuX8c4uIn/Ch
; ls+xOOThuLV+Wjsf/n9JPU5Q29WrLzrnAfvo2aMMRMmf//yipnnNLZ+jdcjDs04nqccpueNSwtHR+a
; mptacOH15yZpQmSo/uMDOz5MzExC/ebAk6reVzpIc8QtbpwlXKWe0ckW7tRTgcPew8ouf4+NJz6e/R
; mjQ97PDKK+5csnDp/Fzh5jW0av9wD3mkvlVdarWXKKZF7R+K3rZEmbGt8tBD/bbKYsfs7HmfSPBQKa
; Z2+Ryq3janG3e5RZKimJa1f0rSJwrfR/TsE0OLF/fck0/wlIKOts6VE3RKlNnlXiQMrdadjxd/yNG5
; fP+mm77cJ4YWEZDgufFGmgY2DjrWd1zmgg6FMrvSA+Fd9u3b9zSKcXV5xyU6vn379hf27t17HC/E/f
; 2rr/7q3K5d5/fRc4Fjx47z5y6/nHdqxEfPBx544Lg0R8IFgs7+/ftnKazTlX6IFb158+aXpfeMtLwA
; nMFtt932D8m2ChJDzz7bR8+FBiR4fvWrpU1zy3/T3Xzzzf/q8m5NHzWnpqZeohQmcKXO+286f6W2dq
; 2fVOdjyuzPxKH9Vr3t/v19Ymih4PDh8+Z+8INLmuZX6o7LLu7WjLcVKYlWV+t83ICk7EIJtTsuWy4+
; 8kD0vOOOXm876picvGDuO9/hVSMAauVzNGv9xChtB5YSrY7a+XCRSGv9xKDqDaWXk46NXdzrbUcQSP
; Bcfz3/kLOfM5SzwLVyki3OgHI0LKe3dZzOx6tderdmS+2fFjFECCSGtm3rt1VGBdu3f+5sq86VKzCX
; ykU9WsrnxGIIJ73jspWjS+64lAwgHMr09H0vTExcfKZPDA0vnn/enUveXXymhWJKi7215jWk5XNCMY
; TTOIXNoZit5TJzA8jR28Z8vz+IPZzAQWa/DcLNa2jeccnJa2jV/vFBx0kewl1wkjsuSy9SoywlD+q3
; VXpqOxxIHWSm5DWs7rikBB2LM5lO8yVyFNPyQKlH7kwcle8jevaJocGBcpA5l9ewviYyl9eQUubOFm
; Y4gL7D4d8t2ooHMKQfXL7f620Hg5LONUZMMbu64zIOOpQ7LoduYfoXgRc7cODArHbNzVq7UCsdOXLk
; aIucD+j1tt1AcpAZyh3YGIuyq7kFYC7jbk0sUEtn4CweGvL9Lu/WBDxlHhsb+0Aihuj1trZo0bl6+O
; 9NzC2tRCJ1UfocifWnmbPqfMj3u7hbM8X3pWKI/iC2PjR0rikbW5aTzJ0Ftgw6zrrzqQHU/kiv8X2p
; GKLX2+rgscfada6wXSmJZ1VOslY+xyroOI3vP07tH827NTl7olLBcq+3laFV5wq7ce641KSY3uHXnq
; UddOZr/khXO7dmT/giEr1t656oVG/7619/4/Ts7GfOjtKiGCSQ4Fm37ttNm/2tm/bSGsat5XOkhzxC
; 1ulaObrGHk7L3Zo1ykzte0vSwO+Jrlhx5UfT0xf00bMCJHiWL//+6RaKKY18rRRTuifaGnTQ37B8jo
; sXCWUAa3yf+yLUAeTW+qQMIMUhpRZyfxA7DyR4fvnLpR8ba+pC09y051BM7fI5nLxGSkboUi+SG0AO
; 3+eiRjGpfL9lAEsOqUaZe73tx1G6sKdGMSUHGyg2zlFMq9o/taBTkhG60ouEq93qgs5UR8PIZFEuMz
; WAsUfnUOZeb/s/UC7sSVFMzYMNJRunKKb1fiSQCjo1yuxKL+IHsIvOxwMIzwl1h6UGMob36GvWrHmn
; hTIvVr0t98KekGJ6G3elDvNBBzbuSioKeOezcePGExSH72oPQ1Wv6enp57paHN5wKFoEOZ9FGZMSJi
; Ym3jh06NATrXR9seltJRf2QDqJse7axuEdl10VmAOwhh5//PEjFLrucj8I+X7Iha0HMOT7XZxK8Yjf
; UbIvhcW50PW2Whf21PIaFjb2lFm6dcZBOI8piVZX67z/d429R07nw3+X7kvVkOP7UjGE19uO0oKjQK
; pzTR1kbtk6a7FxPIesv29zWeZa0HGUzscDKK31Q+18/H+069tSEjyhQ2o5Fb+Q9LYaOtdSEk+qzso9
; 0y+Amo21M8KUs8C5oOOoEzQ3gFL6wUmRawqW8fucFLnUo4/6xUfQuf7oR7IbmamfBVrlJONNe6qNpX
; pb7lngVKbaSTbtJRxdQiGkA9j63Sr16KtW3fj+4cNf+XDUEkO7d3/h9OrVP2U7JMmmvTSv0Vr7R5rX
; aJWKxnkNJy1c1LLANGr/tCQNtFQlXIcUM5JRSQz5C3ta5G0am/YteQ2t2j/cvIZWotIHHSfpfDyANY
; pJ4futL1KjmC21PikToOaQcidvhv0gdpzg4WSqtTPp1LyGdu0fal5DU0box9ppPCheJCmKqd35+EVy
; Hp3L97ntlpIGtYg+jHrbWOeaWyQpitmVjePx5OZIWmycCzpWtX+c5sP8i8Qes5XvcxEnDTQoMwWxQ+
; JO0GE5iA2d61VX1Q8ypyimlc41Z2NvU7RHPQusbWPNKxViOKsXweLYsWPH87jnsrUoVgswYJs2bXp1
; 27Ztf+1KRgh4h4RJ0kKZB30Q+/e/v5B9kBmTFTYGuqq7420M22Kcu7YxFiaUcNZSUWf1YHi0mZmZp6
; AN7PJuTRhp69atL27YsOGEpRgiZTS8J6SEo3TxkfTCHtxjCkc4KBtrbJ1xbIwgAymhdYE5Z9V5z/el
; 8jYOYr5vIYZIIT55IxVDdHXxkUTnGifxupK3xUk8q1o/MVJ3XFoWmHOaDyvxfcu7NUt8X1MMkUIuAy
; kVQ/jEkMW2ikTnWvp+tpS3lZJ41prqXBIv1NtqBx2ntdopA2Oht6WmyLU9OjXBI/Xo2gexd+78lLrO
; NWVjTYpJTeJpl5OkngXWPuQxv10iXe0tKXINwXJLilzLo3MzkNITFD56njjx6eYiYNgGoRxkrk08ro
; 0lFLMlErbW+onBLZ+jFXQ8ZXaSExSSTXsJR+eUy8wNYItHly5stNfqkGCfycmxt1sSQ6Cuk5M/frcl
; tS/ZtJdQTMmeqCSvIZER+rnZmtcIGYkLX4R6gkJz055LMbXO7nE9utaeKMaL45DiCco9iO0v7OE6JM
; 1Ne668TWvTnpvX0LzjkpPXSFFml5qspdVuUfuHEomofJ87gDWPbqEqoSYNSpS5prf1OtfcZC05JItN
; ewrFtNi0p1JMi+QRJejkGInLTcR4AK0zXyWPzuX7XOSSBprlMlPIeXQqZc7pbWsHmUsefZA2tty0zw
; UdSxlhyZY1yuxyDwxXu3XnUwOIttBhzVqftQEMHVJXMsLYo3Mpc6i35R5kDh3SIGwMJ+CpfRc2joNO
; VzLC2CFRTt64ZZXJiqJFUHcMohgX2rYsW5lqF8W4BnHvIgx28ODBJ1tr52JbpeXCHrS1b9++p6HSst
; abxmO9fv3612HjLiWbwPj4+FuwMRZKVzJCAA4Jd2tSHL4rGQyTExNVe1+qBk+nMFG6UJN4+Gi1cuXK
; 91oz1S0Io5X1dYUh0AbGGZI6TNYubeznFO4xtZa3pWyM8pVWYoiSjTHOlM+F/wKeJnw8C/8pqQAAAA
; BJRU5ErkJggg==
; thumbnail end

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M104 S215 ; set extruder temp
M109 S215 ; wait for extruder temp
G28                                        ; move X/Y/Z to min endstops
G1 Z0.28                                   ; lift nozzle a bit 
G92 E0 
G1 Y3 F2400                                    ; zero the extruded length 
G1 X180  E40 F500                       ; Extrude 25mm of filament in a 5cm line. 
G92 E0                                     ; zero the extruded length again 
G1 E-0.2 F3000                                ; Retract a little 
G1 X181 F4000                              ; Quickly wipe away from the filament line
M117
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
M107
;LAYER_CHANGE
;Z:0.25
;HEIGHT:0.25
G1 E-2.5 F4800
G1 Z.25 F9000
G92 E0
G1 X134.75 Y134.75
G1 E2.5 F4800
G92 E0
M204 S5000
;TYPE:External perimeter
;WIDTH:0.499999
G1 X85.25 Y134.75 E2.2505
G1 X85.25 Y85.25 E4.501
G1 X134.75 Y85.25 E6.7515
G1 X134.75 Y110 E7.87675
G1 X134.75 Y134.69 E8.99927
M204 S20000
;WIPE_START
G1 F7200
G1 X134.75 Y134.75 E8.96127
G1 X130.863 Y134.75 E6.49927
;WIPE_END
G92 E0
G1 X123.08 Y85.61 F9000
G1 E2.5 F4800
M204 S5000
;TYPE:Internal infill
;WIDTH:0.5
G1 X131.666 Y85.61 E2.89036
G1 X134.39 Y88.334 E3.0655
G1 X134.39 Y85.61 E3.18935
G1 X85.61 Y134.39 E6.32575
G1 X85.61 Y131.666 E6.4496
G1 X88.334 Y134.39 E6.62474
G1 X97.124 Y134.39 E7.02438
G1 X134.39 Y97.124 E9.42047
G1 X134.39 Y99.848 E9.54432
G1 X120.152 Y85.61 E10.45978
G1 X122.876 Y85.61 E10.58363
G1 X85.61 Y122.876 E12.97972
G1 X85.61 Y120.152 E13.10357
G1 X99.848 Y134.39 E14.01903
G1 X108.638 Y134.39 E14.41867
G1 X134.39 Y108.638 E16.07444
G1 X134.39 Y111.362 E16.19829
G1 X108.638 Y85.61 E17.85406
G1 X111.362 Y85.61 E17.97791
G1 X85.61 Y111.362 E19.63368
G1 X85.61 Y108.638 E19.75753
G1 X111.362 Y134.39 E21.4133
G1 X120.152 Y134.39 E21.81294
G1 X134.39 Y120.152 E22.7284
G1 X134.39 Y122.876 E22.85225
G1 X97.124 Y85.61 E25.24834
G1 X99.848 Y85.61 E25.37219
G1 X85.61 Y99.848 E26.28765
G1 X85.61 Y97.124 E26.4115
G1 X122.876 Y134.39 E28.80759
G1 X131.666 Y134.39 E29.20723
G1 X134.39 Y131.666 E29.38237
G1 X134.39 Y134.39 E29.50622
G1 X85.61 Y85.61 E32.64262
G1 X85.61 Y88.334 E32.76647
G1 X88.334 Y85.61 E32.94161
G1 X96.92 Y85.61 E33.33197
M204 S20000
;WIPE_START
G1 F7200;_WIPE
G1 X92.973 Y85.61 E30.83197
;WIPE_END
G92 E0
M107
;TYPE:Custom
G1 Z2.25 F600 ; Move print head up
G1 X5 Y209 F9000 ; present print
G1 Z70.25 F600 ; Move print head further up
G1 Z150 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84; disable motors                    ; disable stepper motors
; objects_info = {"objects":[]}
; filament used [mm] = 79.63
; filament used [cm3] = 0.19
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 51s
; estimated first layer printing time (normal mode) = 51s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = D:\\1111(已去底).png
; bed_shape = 0x0,220x0,220x220,0x220
; bed_temperature = 60
; before_layer_gcode = ; BEFORE_LAYER_CHANGE [layer_num] @ [layer_z]mm
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 5000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1.1
; bridge_speed = 30
; brim_separation = 0.15
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 20000
; default_filament_profile = "Anycubic PLA @MEGA0"
; default_print_profile = 0.20mm NORMAL @MEGA0
; deretract_speed = 80
; disable_fan_first_layers = 2
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = ""
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.95} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84; disable motors                    ; disable stepper motors
; external_perimeter_acceleration = 5000
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 40%
; external_perimeters_first = 1
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.98
; extrusion_width = 0.42
; fan_always_on = 1
; fan_below_layer_time = 600
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_layer_change = 0
; filament_settings_id = "Anycubic Kobra 2 Pro-PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 10%
; fill_pattern = grid
; first_layer_acceleration = 5000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.5
; first_layer_height = 0.25
; first_layer_speed = 80
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 200
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = disabled
; gcode_resolution = 0.012
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 20000
; infill_anchor = 10
; infill_anchor_max = 10
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 15%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 1%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ; AFTER_LAYER_CHANGE [layer_num] @ [layer_z]mm
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 20000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 20000
; machine_max_acceleration_travel = 3000,1250
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 5000
; machine_max_feedrate_e = 100
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 16
; machine_max_jerk_e = 20
; machine_max_jerk_x = 20
; machine_max_jerk_y = 20
; machine_max_jerk_z = 8
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.28
; max_print_height = 250
; max_print_speed = 300
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 60
; min_feature_size = 25%
; min_layer_height = 0.08
; min_print_speed = 25
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}-{layer_height}-{print_time}-{month}-{day}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 100%
; overhang_speed_1 = 50%
; overhang_speed_2 = 50%
; overhang_speed_3 = 100%
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 10000
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 120
; perimeters = 1
; physical_printer_settings_id = 
; post_process = ArcWelder.exe
; print_settings_id = Anycubic Kobra 2 Pro-PLA
; printer_model = 
; printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_ANYCUBIC\nPRINTER_MODEL_Kobra 2
; printer_settings_id = Anycubic Kobra 2 Pro-PLA
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 2.5
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 80
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 5
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 6
; small_perimeter_speed = 40%
; solid_infill_acceleration = 10000
; solid_infill_below_area = 15
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80%
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM104 S[first_layer_temperature] ; set extruder temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28                                        ; move X/Y/Z to min endstops\nG1 Z0.28                                   ; lift nozzle a bit \nG92 E0 \nG1 Y3 F2400                                    ; zero the extruded length \nG1 X180  E40 F500                       ; Extrude 25mm of filament in a 5cm line. \nG92 E0                                     ; zero the extruded length again \nG1 E-0.2 F3000                                ; Retract a little \nG1 X181 F4000                              ; Quickly wipe away from the filament line\nM117
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 1
; support_material_closing_radius = 2
; support_material_contact_distance = 0.28
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 80
; support_material_style = organic
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 1
; thumbnails = 230x110/PNG
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.42
; top_solid_infill_acceleration = 5000
; top_solid_infill_speed = 65%
; top_solid_layers = 0
; top_solid_min_thickness = 0.6
; travel_acceleration = 20000
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
