; generated by PrusaSlicer 2.7.4+win64 on 2024-05-20 at 21:56:13 UTC
; Postprocessed by [ArcWelder](https://github.com/FormerLurker/ArcWelderLib)
; Copyright(C) 2021 - Brad Hochgesang
; Version: 1.2.0, Branch: HEAD, BuildDate: 2021-11-21T20:25:43Z
; resolution=0.05mm
; path_tolerance=5.0%
; max_radius=9999.00mm
; default_xyz_precision=3
; default_e_precision=5
; extrusion_rate_variance_percent=5.0%




; thumbnail begin 230x110 7232
; iVBORw0KGgoAAAANSUhEUgAAAOYAAABuCAYAAAAziW8OAAAU90lEQVR4Ae1dX4jXVRa/Dz204UMs7e
; KDLLIbrA89BBtsbMEKhSBrBAaRuGCy1oqhaMkgQ6Zo7DiVmjOoo5UyajROTqVOyexOTZu7ram5TeGG
; RRTUssvSQw/CPMzDbz0DR263++fce879/r7f+d2HD+XofO/33nP/fL7nfO45auHChS0bHnvssW/279
; 9//pFHHvnvAw88cPX555//8Omnn77s+vdSWLZs2XfQ1oYNG75asmTJ1FNPPXUF/gzvkLNd7OMzzzwz
; Ce1C+y+99NL70P+c7S5atGha7+OKFSu+hXah/dzt2mwM75KzXd3G0H67bAz9RxvDmOcea72PMN5Hjx
; 59z2djFerIyMjI+PDw8NswiDlf3uzI7t27Lx0/fvwdGMQq2+3p6flkdHT0DExYmDRVtQ2T4+TJk2Mw
; UWDixv7+2rW3tbq6FkS3C22BjYeGhiY6ycanTp0ag4UCf66qbViQVBsrXwfghOzv77/Y3d39OXQi98
; 6C2LRp0xfw8lu3bv0UFkhVEwbagZ2sq6vrC2gX3qMKw8EGCO1t3rz5MxhzPLWpv//CC3Nbk5NqBvD/
; ixffTfo93cbQ13bYGE6Sdth448aNX9bZxsr2Q1jNJp3S6UeujuiUGdswKWaOdk2q4fpZDpiUGSkWUk
; zf7y5ffkdrYuLG64sS8dZbc2ZOUN/vttvGOmU2KWYn2Bg2BJ+NlfkD3DltL4o7LAygdEdwJ7O9qN4R
; 6R0ddzJ4vu3voT3c0SUnDWwyMM4A24aDiwQmjq3dHTvm/2BB6jh37obWli23Wk9Pqo2lN8K62hjeJ4
; eNccNxUWafjRX15c0BlqIfOBFcE9TsiCT9QDoVmgjwXpKTFT/+Q+OHk1WnmEuX3jlzIvoWpY6RkZtn
; fqfTbRz6poOxkbQxbkIpNgYofEisB1KCftjoFMXIXPpho8yUdqkU04eUd8edtbf3rqvUBWmenn19v7
; 7aiTaO8TJTKGaud8cNCU9tBYNO2clCHYmlHz46RUEq/fDRKeoA+iimb6JQTysTQEcHB382nbIodZw+
; /dNpqmOo2LhaG+NY46mtJKhKDP3Al5eIl8XQjxg6RRnAGC8mlTLb4HLwpAJOz5BjSMrGqRO002xsAt
; ak4j5E70joCE+hzNQB9NGPFDpFQciLyaWCfX3zxBakCXh2yukZsnEOYUa7bew7tVM+iyhQkp0A2OgH
; /JdDmakDaKMfaNBc7nCXF5P68W8DnJIxDp5UQBvQloSNQ15mKRsj2zJtnDPkEbJxDnWYytERnX6sWb
; Pm36kTNGUA0Ujr1q37WooyU4BeTNixOXQKQhy5F6RJbV1hFaqNV69e/Z922BjHXIIyV2ljClSuTsAA
; vvLKK++C3Cu37tMEDBrI6nIGrF2GGxsbGwVKFdsuLIxjx26pdFHq0MMqsTYGyWbVNkbpZDtsfObMmT
; dTbBwDleOh+sd/qocrBTpllo5LhYCUGfob68Vcter2mZOrXYtSPz2pelvTxjaKmcvGSJnbYWNoN8XG
; sVDSD7Qp9mM9XClwBe0lA+U2uLzMVC9mTgdPKkJ6W5sHshNsbFJmaTGEDiX58iEPZMjDlYqQpzCXFj
; P08e/zYkqHQaRh09t2qo19XmYJMYQNSoJ+xHggXR6uFMTEyyS1mLFeZtOLWbWDh0Nt0TFUbEy3Madd
; APRBcegHJ6DLpR+pl1y59IOqc7VNsJ6e7isTE7+4OjmpWk3C2Ni8qX37nrxcbBy2MWdD0j+LlN6RGP
; qBAV2OqzqFfkhQllT6waEs4FRp0mJ0nZ7FxuF2U05tkzIr/YHU1U5V7Et3hBO0t4FKP7gSM/0ic9MB
; YZWcetum2tgE1VPtoszKNjCujuTMC+OjHxzKHEKIfnDywtTdwcM5PaX1tk21sQ+6p9p2Avsos3J1xK
; QSOeVHekdMKiFBmakDqGsxuXQqdJF5NkBKb1u1jXEB5vLkmrB9KoYoswp15MCBA+cgJ0xO+ZEJpB+9
; vb0fS1HmmAHctWvXP+uuc60LuHrbJto4BcgIIAEZhTKr0OCBpO7FF198P0cQ1QXYRQYGBj4AVKXqwM
; EDqRcYDBUeMb/flDCINFIcQ2DjQ4cO/X3v3r3n22HjwcHBszmF7zYAZX799df/TLmIrVx/oR+1uYKo
; NuiU2UYxc8GkUzGe6nbrXOsCqt7WZePcGfo4NubApMyUq2LK9hDXUSsZRDXhC+jm1mK6vMwUT3VddK
; 51gc8xRLFxLmbGsTEHLi9zaENS+h8o3qkcwmFKZmrdwyX1PUL1Mrs81XXUudYFpmMo1sZSzIyaMUPP
; Si/RLtXLrFce0DckpU9QqndKkn7EUmQp+hHrZdbHaOXK30x3koMnFegYapqNudkIYr3M+qmNY6Q4AV
; 0OxeQEdDn0I1YDaf7uq6/e/02TFke7cenSTTNjlhJWaZeNOYcOR3yjMzPFpQ0p9EMqoBtLPyh0ygWY
; WODcaNKiqBNSLmJXbWMdLorpgpT4Bp+jOA8xOxKiHzkCulT60ck617og5iK2a9LnsrENNoppg7T4Bt
; pVEg+ydcSkENIaSLNdF/0oOtf6IabwkWlj200oaZ2rbeHZnH8cyhyCytkRjFNVFQM16UfRudYXlMJH
; PhsjM6uqxqVZ3EqKMle6MLEjoBiCZE1VZaoDgLFA9nTixIlx2ByKzrW+AGoLY51yemJtTVfBnlxzC0
; 5lnFs5DxqV68HQgcOHD/8Na1xWVXcRKTPIrmLFEJ2mc60LwDEUo7fl2JgDvcZlTjFEloVp807FerhS
; YKPMJv3w/X6n6lzrAorelmtjDkzKnPsTTUk+LFT/MFdtTd/HfyguBTSqOHjqA1dYhWNj7tzyRRJy1d
; ZUEh2JueTKzQNjglrMxabFLA6eesLU21KD9tJ6W2okQVqmCs9TXIqZUsxFgn6k1j9E+lF0rvXHwMDP
; p/v7/zSZamNO3p7YZ0jdhELKrDgUkyM45tAPTkAXTsnx8R9PT06qVkH98d57c6ekCh9RN3xOTJRTW1
; OnzEqf7FSKKRnQjaEfMZTZhuLgaSYkCh9R5otUkjmfGMIGG2VWrlXr6kgoM3VqR0LUgVP/sFxknh1I
; LXwUophSOlfbnNXFEDHzXvk6YtamyF3/ENqz0Q8OZS4XmWcXUvW2LoqZO8mcS6YaYp3K1xH8xSrrH+
; r0AxdqKmUuDp7ZC67eFhZi7hqXOvRPRQplVqGOgOwJ6h/mzrljtgtJmk6dOjUGgxf7+yUM0hlI1dvC
; 5xDUuKxSzgeANQTtwiEXale5/kI/anMFUV2LEhX7K1eu/F+sh6s4eDoLsY4hPT1NlbU1dcpMiUYo14
; 5iBu1z5Pqx7SgmZaZ6uMpF5s5GyDHk+qaTFrzYDhobZQ5FI5T58j75kVQQ1QaKV9bl4SoXmQsALr0t
; HjQhr6x0RvZQJIHklY25yCxZvj22/qF5aheda4EJLHwUE0mQ1tvGRBJsaWFVatA+NohqQ+olV+jA4c
; ObLhcHT4ELcHqePLn+cixF5eptU8U35qei4hZzSUk1WAr2FFQFqcJH1AODI77RT20lVeOS6hji5P4p
; F5kLUsAtfBSaq9LiG1iTivsQc9G5OlJ0rgXtBKcitu/QSS0LH4KSfBh2xKSpnPqHRedaIAlJvW1jMh
; jYOsKpf/jww0XnWiAPmFPr16fpbWFOb9++/V8502VmW5gA2EWOHTv2V6iBmOrhWrr0jtbQ0I2tixeb
; ZfiCeuPYsRtaS5bcnjSvYS5jjcucxXZVjoea9Q85R/6999597dtg7rVdrlnGL6gfLlxQrSefnJt80O
; ifaLlrayrJh/kyU3Nra65YseBaXKrQ2oI0jI2p1kMPxdNX/aCxZWLPJVNVUqudkpmaq7e97747Wjt3
; 3lKobUEU9uyZc20RxRc0okYScuhtlYRXKYaqcvW2QG03bJjfevPNcnoW+DExoVqrVs1PmtOxkQQpve
; 31al8cisnJ/cOprQn/vq9v/ZU33pg7VU7PAhuGh+dO9fQ8fiWFmaXm/uHqbXXKrHCBxVJMiWIuKeXb
; dcoMp2d397ziGCq4DnDwPPHEvOsTPYaZUcvCUw4dmNPUaISNMivbavd1JMcVGaqHy0WZH3zw9pmwSp
; MmUIE8hodvuBZiW2Cdr6H6qTlqXMJ8DaWFdVFm5VokNoqZu8al69SmUGY4PbdvL46hTsWzz7odPD6K
; 6YskSMD3qeijzMrXEaSYeiwydxoG08MVS5lXrbq1OIY6CODgWbmSpoE1i1vlrnGpHyyw+PHQoVBmFe
; oIKHegzmWVNS712poplBnCKgcPzimn5yzH/v1zWosXx90aQWYGJSJz17g024XDDpLbUSiz8v0l1rjc
; uXPnR1UlLQLAafnyyy+/+9xzz32U6mACatvVNe/ajlpOz9kGOCXXrp2XNLfwtAINd5W1NZEyDwwMfE
; C5iK1cL29mps6dtAhf3nTwxHq4TBTH0OwC6Fzvv/+2pPllfhZVVVvTpMwUmaoyf+DzTlE9XCkI1T8s
; etvOBoRBduy4uXXPPXHZCMwFaM5b6Vw/Jnzz1lV54HsLkyo/ytERakBXQm9bHEPNA1DX5cvjLzkDqJ
; EE6dqaVPENrDVbNELhS8UW7OFSTHx5kzJTfkf3cMW2CY6hPXtKWKUp2LfvJ9OpOtfYSAKXmSFiIwnQ
; LvyOriFQ3BqXqbU1OQFdzqkN7zkwsPf8tm0LpopjqL6AU7K7e8FUqo05F5l9FDPULkd8o6eFVRK3sG
; MoJjf3j9mRGPphUmZ0DJXTs17QLzJzbZyKWJmqlPgGDx3FeYhrt3B1hFPjMtQR36nvo8xFb1sfuC4y
; UyhmymcRZW6ZFDPl3VKgpB6kLxIb/eBQZgpc9INKmeH0LBex24fTp8MXmV3FrXLXuHRVHpCsrJ51Ye
; odwRfW/z9HWzp0DxdSkRjKDKdnuYhdPXw6VxM6xUyxcSrMygNSlLnShYkdGRwcPAuJi6pYlHq7kMVs
; dHT0DBgv5Rlr1xa9bRVIvcgMNt69e/clqJ+aauNUwOkMcwsOmxy5frIuTD0zdZW1NQG4q0EVbBv9oA
; Iy9B09WvS2uZCic5W2ccqiRMqcuySlkn6gLTO1K4gqCRvf5xY+QsfQ2bPNmvR1hoTOVdLGFLgiCTll
; qkryYT7vFMXDlYpQMRdfbU0Kit5WBhI611w2diEUSchVW1NJdCTGOyVZWzO2/iHn1Ea9baG28eDoXM
; FWVdnYBDWSIC1Tncn5w+0IeqdiXkiCfqQWc+HSj8cfv+vq+PhN001aGO0EUNdNm36b5Llsl41TwyBc
; va1OmVUqxZQ4wlPpBzegm/ruSJkfffS+7/btu7mcngFAPtdly353NcX51y4bhygzZXGlvLtJmZW5SC
; gUUzL3Twz9kAzoxtAPW16YchHbDdPB0wQbx1BmCmJkqjbKrGwdcVFMSZ2riRD9kEiXaUOIfoToVNHb
; fh++gj0hG6d8FlVh41SE9La+TUi5OmJSTE6Ny5iOmPQjl9dLh4t+UClJ0dvSC/Y01cacdm1pYUOUWf
; keiKu9u7v7c3hIFYmL9I5s3rz5s1zpMm1A+rFx48YvU+hUp+ptYwv2NNnGqdDTwlIos/I9DBbiiRMn
; xo8cOXK2qoFDw+3du/c8yPmqUnUgtm7d+ilIvWAQU+j64sV3dpTellOwB2w8MjIyXrWNe3p6PsEal1
; UlmAOgnI9C15XvISg/qoJqIHTKnOtKjQ3mtTUb/aACqO1s19tKFOzB/K5NtHEs9D5SKg8o8wc2DyT+
; PGfSIoBLsZ9bb+vyMnMKHwFmq9720CGeztWWz5Wbz6ldNg7B5eAJeaqVOTihzNTSSYv0l/ddco29UU
; 4BxcsspbedDY4hvWDPbLWx5DUuSiTB5alW+D+xNS6l6EfMJVeXhysFsV5mbmnvputtbQV7mmJjasYM
; qfLtsZ9+tn+vOAFdDv1wUeaYAUylH6mXXLlazPXr//jNkSO/+rZp1PbIkV9+t2HDHxpp49iDg2vjVP
; ENbkh4wipuQDeFfkgUc0mhmBQ6RR38mA3JpFNNKXyEBXs4NuZ8M6ZQzLrYOLVd3JCUxHdiDP2Q9sBR
; 6Yd0XhgqXXFR5roXPjIvMsc4/4qN+etJSTzIHEAb/ciZuMhHPzh0itKub7KGKHMd9bahi8w+599str
; GLWebK/aMkH6Z3RKcfuXSuJkz6UVX9Q3OyxqZSrItjiHqReZElZWi7bZxbAGNWHpCizC6onB2B2pqA
; KoQJCFwUMEmqCFoj0FMNZQtT6FQ7Cx9BGGTLlluiLzLr9VPbYeODBw/+ox02hrmVM10mQOV6MNa47O
; /vv1hlbU0w0oEDB85xamumGg36CZOlSYWPQOfKKdjTbhvnFLy4bIw1LnOe0irHy5vFXLg3yqkw6VQO
; MYQNJmXmBsqrKnzE0bmaHki0cW55m83Gevn2Km3MKW4VgpJ8mO/jP6feNlT/MKcW0/VsroQxp2MIHD
; xr1sxP6q/PA5m7fqrPxqnFrdppYx+U1GqneKdCHq4UUAO60lpMqgeSe2pLX8QeHLyRpXOl2lhyss52
; G9vGUHE7EuuBlOpIykkopcVMqX9oSx9BBeptL1z4UXISMHDwdHXNbcW2zbExl2KmBO0pxa3qaGMEUm
; bFoZjcGpepFJMTL+Ps6BL1D1O1mDBWu3at/iLlIvbIiGpt2/b7r1IoJtfGqRQT/n1q0L6dNk6trYk2
; xvWgUjqSspO5EEs/pAK6sad2qgbSNXbUHd3chOD03LGD7hjCgj2xEkbJoH2s86/pNo6tPGA7aJTZET
; 2IansIGFW6xiXFw5VCpyiTL0Q/cjmPKF5MH50KXcRGnattsoYoZg5hBoVi5rJxyH62SIJEuxwbq5iO
; SHBoX0dcp7a0BnKhZbLa6EdOiZk5Ec12MS+Mb6eHi9iHD/9Qbxsq2OOjmDk92O20sYti5raxr7amjz
; Ir1wN1ipn75c2OYFtICXJoIG2TRqcfuTSQtnZ1ihlLp9AxBGGV2II9OsXsBBubFLPONla+B4Kxjh8/
; /s7w8PDbufWmZkd6e3s/hqRYMJBVtQuAjICQMAkGscp2wWCvvfbaX1InCoRVUgr2gI0hMdXQ0NBEbg
; GIaeO+vr4Pq7YxtIsJ19pp4xAjUa6/wMzUILeCyVql9Emvf5jq4UoB7mTr1q372kY/cgFPKxjnnIFy
; W7to41yBcheQMmN5jk6xMYwzxTH0f00odz0GJjSZAAAAAElFTkSuQmCC
; thumbnail end

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M104 S215 ; set extruder temp
M109 S215 ; wait for extruder temp
G28                                        ; move X/Y/Z to min endstops
G1 Z0.28                                   ; lift nozzle a bit 
G92 E0 
G1 Y3 F2400                                    ; zero the extruded length 
G1 X180  E40 F500                       ; Extrude 25mm of filament in a 5cm line. 
G92 E0                                     ; zero the extruded length again 
G1 E-0.2 F3000                                ; Retract a little 
G1 X181 F4000                              ; Quickly wipe away from the filament line
M117
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
M107
;LAYER_CHANGE
;Z:0.25
;HEIGHT:0.25
G1 E-2.5 F4800
G1 Z.25 F9000
G92 E0
G1 X134.75 Y134.75
G1 E2.5 F4800
G92 E0
M204 S5000
;TYPE:External perimeter
;WIDTH:0.499999
G1 X85.25 Y134.75 E2.2505
G1 X85.25 Y85.25 E4.501
G1 X134.75 Y85.25 E6.7515
G1 X134.75 Y110 E7.87675
G1 X134.75 Y134.69 E8.99927
M204 S20000
;WIPE_START
G1 F7200
G1 X134.75 Y134.75 E8.96127
G1 X130.863 Y134.75 E6.49927
;WIPE_END
G92 E0
G1 X130.558 Y134.39 F9000
G1 E2.5 F4800
M204 S5000
;TYPE:Internal infill
;WIDTH:0.5
G1 X134.39 Y134.39 E2.67422
G1 X134.39 Y130.354 E2.85772
G1 X85.61 Y130.354 E5.07549
G1 X85.61 Y126.283 E5.26058
G1 X134.39 Y126.283 E7.47835
G1 X134.39 Y122.212 E7.66344
G1 X85.61 Y122.212 E9.88121
G1 X85.61 Y118.142 E10.06625
G1 X134.39 Y118.142 E12.28402
G1 X134.39 Y114.071 E12.46911
G1 X85.61 Y114.071 E14.68688
G1 X85.61 Y110 E14.87197
G1 X134.39 Y110 E17.08974
G1 X134.39 Y105.929 E17.27483
G1 X85.61 Y105.929 E19.4926
G1 X85.61 Y101.858 E19.67769
G1 X134.39 Y101.858 E21.89546
G1 X134.39 Y105.726 E22.07132
M204 S20000
;WIPE_START
G1 F7200
G1 X134.39 Y101.858 E19.62159
G1 X134.311 Y101.858 E19.57132
;WIPE_END
G92 E0
G1 X85.61 Y93.92 F9000
G1 E2.5 F4800
M204 S5000
G1 X85.61 Y97.788 E2.67586
G1 X134.39 Y97.788 E4.89363
G1 X134.39 Y93.717 E5.07872
G1 X85.61 Y93.717 E7.29649
G1 X85.61 Y89.646 E7.48158
G1 X134.39 Y89.646 E9.69935
G1 X134.39 Y85.61 E9.88285
G1 X130.354 Y85.61 E10.06635
G1 X130.354 Y134.39 E12.28412
G1 X126.283 Y134.39 E12.46921
G1 X126.283 Y85.61 E14.68698
G1 X122.212 Y85.61 E14.87207
G1 X122.212 Y134.39 E17.08984
G1 X118.142 Y134.39 E17.27488
G1 X118.142 Y85.61 E19.49265
G1 X114.071 Y85.61 E19.67774
G1 X114.071 Y134.39 E21.89551
G1 X110 Y134.39 E22.0806
G1 X110 Y85.61 E24.29837
G1 X105.929 Y85.61 E24.48346
G1 X105.929 Y134.39 E26.70123
G1 X101.858 Y134.39 E26.88632
G1 X101.858 Y85.61 E29.10409
G1 X97.788 Y85.61 E29.28913
G1 X97.788 Y134.39 E31.5069
G1 X93.717 Y134.39 E31.69199
G1 X93.717 Y85.61 E33.90976
G1 X89.646 Y85.61 E34.09485
G1 X89.646 Y134.39 E36.31262
G1 X85.61 Y134.39 E36.49612
G1 X85.61 Y130.558 E36.67034
M204 S20000
;WIPE_START
G1 F7200;_WIPE
G1 X85.61 Y134.39 E34.24341
G1 X85.725 Y134.39 E34.17034
;WIPE_END
G92 E0
M107
;TYPE:Custom
G1 Z2.25 F600 ; Move print head up
G1 X5 Y209 F9000 ; present print
G1 Z70.25 F600 ; Move print head further up
G1 Z150 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84; disable motors                    ; disable stepper motors
; objects_info = {"objects":[]}
; filament used [mm] = 102.54
; filament used [cm3] = 0.25
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 57s
; estimated first layer printing time (normal mode) = 57s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = D:\\1111(已去底).png
; bed_shape = 0x0,220x0,220x220,0x220
; bed_temperature = 60
; before_layer_gcode = ; BEFORE_LAYER_CHANGE [layer_num] @ [layer_z]mm
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 5000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1.1
; bridge_speed = 30
; brim_separation = 0.15
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 20000
; default_filament_profile = "Anycubic PLA @MEGA0"
; default_print_profile = 0.20mm NORMAL @MEGA0
; deretract_speed = 80
; disable_fan_first_layers = 2
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = ""
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.95} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84; disable motors                    ; disable stepper motors
; external_perimeter_acceleration = 5000
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 40%
; external_perimeters_first = 1
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.98
; extrusion_width = 0.42
; fan_always_on = 1
; fan_below_layer_time = 600
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_layer_change = 0
; filament_settings_id = "Anycubic Kobra 2 Pro-PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 90
; fill_density = 20%
; fill_pattern = grid
; first_layer_acceleration = 5000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.5
; first_layer_height = 0.25
; first_layer_speed = 80
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 200
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = disabled
; gcode_resolution = 0.012
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 20000
; infill_anchor = 10
; infill_anchor_max = 10
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 15%
; infill_speed = 60
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 1%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ; AFTER_LAYER_CHANGE [layer_num] @ [layer_z]mm
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 20000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 20000
; machine_max_acceleration_travel = 3000,1250
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 5000
; machine_max_feedrate_e = 100
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 16
; machine_max_jerk_e = 20
; machine_max_jerk_x = 20
; machine_max_jerk_y = 20
; machine_max_jerk_z = 8
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.28
; max_print_height = 250
; max_print_speed = 300
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 60
; min_feature_size = 25%
; min_layer_height = 0.08
; min_print_speed = 25
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}-{layer_height}-{print_time}-{month}-{day}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 100%
; overhang_speed_1 = 50%
; overhang_speed_2 = 50%
; overhang_speed_3 = 100%
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 10000
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 80
; perimeters = 1
; physical_printer_settings_id = 
; post_process = ArcWelder.exe
; print_settings_id = Anycubic Kobra 2 Pro-PLA
; printer_model = 
; printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_ANYCUBIC\nPRINTER_MODEL_Kobra 2
; printer_settings_id = Anycubic Kobra 2 Pro-PLA
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 2.5
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 80
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 5
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 6
; small_perimeter_speed = 40%
; solid_infill_acceleration = 10000
; solid_infill_below_area = 15
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80%
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM104 S[first_layer_temperature] ; set extruder temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28                                        ; move X/Y/Z to min endstops\nG1 Z0.28                                   ; lift nozzle a bit \nG92 E0 \nG1 Y3 F2400                                    ; zero the extruded length \nG1 X180  E40 F500                       ; Extrude 25mm of filament in a 5cm line. \nG92 E0                                     ; zero the extruded length again \nG1 E-0.2 F3000                                ; Retract a little \nG1 X181 F4000                              ; Quickly wipe away from the filament line\nM117
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 1
; support_material_closing_radius = 2
; support_material_contact_distance = 0.28
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 80
; support_material_style = organic
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 1
; thumbnails = 230x110/PNG
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.42
; top_solid_infill_acceleration = 5000
; top_solid_infill_speed = 65%
; top_solid_layers = 0
; top_solid_min_thickness = 0.6
; travel_acceleration = 20000
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
