; generated by PrusaSlicer 2.7.4+win64 on 2024-05-20 at 21:53:43 UTC
; Postprocessed by [ArcWelder](https://github.com/FormerLurker/ArcWelderLib)
; Copyright(C) 2021 - Brad Hochgesang
; Version: 1.2.0, Branch: HEAD, BuildDate: 2021-11-21T20:25:43Z
; resolution=0.05mm
; path_tolerance=5.0%
; max_radius=9999.00mm
; default_xyz_precision=3
; default_e_precision=5
; extrusion_rate_variance_percent=5.0%




; thumbnail begin 230x110 7232
; iVBORw0KGgoAAAANSUhEUgAAAOYAAABuCAYAAAAziW8OAAAU90lEQVR4Ae1dX4jXVRa/Dz204UMs7e
; KDLLIbrA89BBtsbMEKhSBrBAaRuGCy1oqhaMkgQ6Zo7DiVmjOoo5UyajROTqVOyexOTZu7ram5TeGG
; RRTUssvSQw/CPMzDbz0DR263++fce879/r7f+d2HD+XofO/33nP/fL7nfO45auHChS0bHnvssW/279
; 9//pFHHvnvAw88cPX555//8Omnn77s+vdSWLZs2XfQ1oYNG75asmTJ1FNPPXUF/gzvkLNd7OMzzzwz
; Ce1C+y+99NL70P+c7S5atGha7+OKFSu+hXah/dzt2mwM75KzXd3G0H67bAz9RxvDmOcea72PMN5Hjx
; 59z2djFerIyMjI+PDw8NswiDlf3uzI7t27Lx0/fvwdGMQq2+3p6flkdHT0DExYmDRVtQ2T4+TJk2Mw
; UWDixv7+2rW3tbq6FkS3C22BjYeGhiY6ycanTp0ag4UCf66qbViQVBsrXwfghOzv77/Y3d39OXQi98
; 6C2LRp0xfw8lu3bv0UFkhVEwbagZ2sq6vrC2gX3qMKw8EGCO1t3rz5MxhzPLWpv//CC3Nbk5NqBvD/
; ixffTfo93cbQ13bYGE6Sdth448aNX9bZxsr2Q1jNJp3S6UeujuiUGdswKWaOdk2q4fpZDpiUGSkWUk
; zf7y5ffkdrYuLG64sS8dZbc2ZOUN/vttvGOmU2KWYn2Bg2BJ+NlfkD3DltL4o7LAygdEdwJ7O9qN4R
; 6R0ddzJ4vu3voT3c0SUnDWwyMM4A24aDiwQmjq3dHTvm/2BB6jh37obWli23Wk9Pqo2lN8K62hjeJ4
; eNccNxUWafjRX15c0BlqIfOBFcE9TsiCT9QDoVmgjwXpKTFT/+Q+OHk1WnmEuX3jlzIvoWpY6RkZtn
; fqfTbRz6poOxkbQxbkIpNgYofEisB1KCftjoFMXIXPpho8yUdqkU04eUd8edtbf3rqvUBWmenn19v7
; 7aiTaO8TJTKGaud8cNCU9tBYNO2clCHYmlHz46RUEq/fDRKeoA+iimb6JQTysTQEcHB382nbIodZw+
; /dNpqmOo2LhaG+NY46mtJKhKDP3Al5eIl8XQjxg6RRnAGC8mlTLb4HLwpAJOz5BjSMrGqRO002xsAt
; ak4j5E70joCE+hzNQB9NGPFDpFQciLyaWCfX3zxBakCXh2yukZsnEOYUa7bew7tVM+iyhQkp0A2OgH
; /JdDmakDaKMfaNBc7nCXF5P68W8DnJIxDp5UQBvQloSNQ15mKRsj2zJtnDPkEbJxDnWYytERnX6sWb
; Pm36kTNGUA0Ujr1q37WooyU4BeTNixOXQKQhy5F6RJbV1hFaqNV69e/Z922BjHXIIyV2ljClSuTsAA
; vvLKK++C3Cu37tMEDBrI6nIGrF2GGxsbGwVKFdsuLIxjx26pdFHq0MMqsTYGyWbVNkbpZDtsfObMmT
; dTbBwDleOh+sd/qocrBTpllo5LhYCUGfob68Vcter2mZOrXYtSPz2pelvTxjaKmcvGSJnbYWNoN8XG
; sVDSD7Qp9mM9XClwBe0lA+U2uLzMVC9mTgdPKkJ6W5sHshNsbFJmaTGEDiX58iEPZMjDlYqQpzCXFj
; P08e/zYkqHQaRh09t2qo19XmYJMYQNSoJ+xHggXR6uFMTEyyS1mLFeZtOLWbWDh0Nt0TFUbEy3Madd
; APRBcegHJ6DLpR+pl1y59IOqc7VNsJ6e7isTE7+4OjmpWk3C2Ni8qX37nrxcbBy2MWdD0j+LlN6RGP
; qBAV2OqzqFfkhQllT6waEs4FRp0mJ0nZ7FxuF2U05tkzIr/YHU1U5V7Et3hBO0t4FKP7gSM/0ic9MB
; YZWcetum2tgE1VPtoszKNjCujuTMC+OjHxzKHEKIfnDywtTdwcM5PaX1tk21sQ+6p9p2Avsos3J1xK
; QSOeVHekdMKiFBmakDqGsxuXQqdJF5NkBKb1u1jXEB5vLkmrB9KoYoswp15MCBA+cgJ0xO+ZEJpB+9
; vb0fS1HmmAHctWvXP+uuc60LuHrbJto4BcgIIAEZhTKr0OCBpO7FF198P0cQ1QXYRQYGBj4AVKXqwM
; EDqRcYDBUeMb/flDCINFIcQ2DjQ4cO/X3v3r3n22HjwcHBszmF7zYAZX799df/TLmIrVx/oR+1uYKo
; NuiU2UYxc8GkUzGe6nbrXOsCqt7WZePcGfo4NubApMyUq2LK9hDXUSsZRDXhC+jm1mK6vMwUT3VddK
; 51gc8xRLFxLmbGsTEHLi9zaENS+h8o3qkcwmFKZmrdwyX1PUL1Mrs81XXUudYFpmMo1sZSzIyaMUPP
; Si/RLtXLrFce0DckpU9QqndKkn7EUmQp+hHrZdbHaOXK30x3koMnFegYapqNudkIYr3M+qmNY6Q4AV
; 0OxeQEdDn0I1YDaf7uq6/e/02TFke7cenSTTNjlhJWaZeNOYcOR3yjMzPFpQ0p9EMqoBtLPyh0ygWY
; WODcaNKiqBNSLmJXbWMdLorpgpT4Bp+jOA8xOxKiHzkCulT60ck617og5iK2a9LnsrENNoppg7T4Bt
; pVEg+ydcSkENIaSLNdF/0oOtf6IabwkWlj200oaZ2rbeHZnH8cyhyCytkRjFNVFQM16UfRudYXlMJH
; PhsjM6uqxqVZ3EqKMle6MLEjoBiCZE1VZaoDgLFA9nTixIlx2ByKzrW+AGoLY51yemJtTVfBnlxzC0
; 5lnFs5DxqV68HQgcOHD/8Na1xWVXcRKTPIrmLFEJ2mc60LwDEUo7fl2JgDvcZlTjFEloVp807FerhS
; YKPMJv3w/X6n6lzrAorelmtjDkzKnPsTTUk+LFT/MFdtTd/HfyguBTSqOHjqA1dYhWNj7tzyRRJy1d
; ZUEh2JueTKzQNjglrMxabFLA6eesLU21KD9tJ6W2okQVqmCs9TXIqZUsxFgn6k1j9E+lF0rvXHwMDP
; p/v7/zSZamNO3p7YZ0jdhELKrDgUkyM45tAPTkAXTsnx8R9PT06qVkH98d57c6ekCh9RN3xOTJRTW1
; OnzEqf7FSKKRnQjaEfMZTZhuLgaSYkCh9R5otUkjmfGMIGG2VWrlXr6kgoM3VqR0LUgVP/sFxknh1I
; LXwUophSOlfbnNXFEDHzXvk6YtamyF3/ENqz0Q8OZS4XmWcXUvW2LoqZO8mcS6YaYp3K1xH8xSrrH+
; r0AxdqKmUuDp7ZC67eFhZi7hqXOvRPRQplVqGOgOwJ6h/mzrljtgtJmk6dOjUGgxf7+yUM0hlI1dvC
; 5xDUuKxSzgeANQTtwiEXale5/kI/anMFUV2LEhX7K1eu/F+sh6s4eDoLsY4hPT1NlbU1dcpMiUYo14
; 5iBu1z5Pqx7SgmZaZ6uMpF5s5GyDHk+qaTFrzYDhobZQ5FI5T58j75kVQQ1QaKV9bl4SoXmQsALr0t
; HjQhr6x0RvZQJIHklY25yCxZvj22/qF5aheda4EJLHwUE0mQ1tvGRBJsaWFVatA+NohqQ+olV+jA4c
; ObLhcHT4ELcHqePLn+cixF5eptU8U35qei4hZzSUk1WAr2FFQFqcJH1AODI77RT20lVeOS6hji5P4p
; F5kLUsAtfBSaq9LiG1iTivsQc9G5OlJ0rgXtBKcitu/QSS0LH4KSfBh2xKSpnPqHRedaIAlJvW1jMh
; jYOsKpf/jww0XnWiAPmFPr16fpbWFOb9++/V8502VmW5gA2EWOHTv2V6iBmOrhWrr0jtbQ0I2tixeb
; ZfiCeuPYsRtaS5bcnjSvYS5jjcucxXZVjoea9Q85R/6999597dtg7rVdrlnGL6gfLlxQrSefnJt80O
; ifaLlrayrJh/kyU3Nra65YseBaXKrQ2oI0jI2p1kMPxdNX/aCxZWLPJVNVUqudkpmaq7e97747Wjt3
; 3lKobUEU9uyZc20RxRc0okYScuhtlYRXKYaqcvW2QG03bJjfevPNcnoW+DExoVqrVs1PmtOxkQQpve
; 31al8cisnJ/cOprQn/vq9v/ZU33pg7VU7PAhuGh+dO9fQ8fiWFmaXm/uHqbXXKrHCBxVJMiWIuKeXb
; dcoMp2d397ziGCq4DnDwPPHEvOsTPYaZUcvCUw4dmNPUaISNMivbavd1JMcVGaqHy0WZH3zw9pmwSp
; MmUIE8hodvuBZiW2Cdr6H6qTlqXMJ8DaWFdVFm5VokNoqZu8al69SmUGY4PbdvL46hTsWzz7odPD6K
; 6YskSMD3qeijzMrXEaSYeiwydxoG08MVS5lXrbq1OIY6CODgWbmSpoE1i1vlrnGpHyyw+PHQoVBmFe
; oIKHegzmWVNS712poplBnCKgcPzimn5yzH/v1zWosXx90aQWYGJSJz17g024XDDpLbUSiz8v0l1rjc
; uXPnR1UlLQLAafnyyy+/+9xzz32U6mACatvVNe/ajlpOz9kGOCXXrp2XNLfwtAINd5W1NZEyDwwMfE
; C5iK1cL29mps6dtAhf3nTwxHq4TBTH0OwC6Fzvv/+2pPllfhZVVVvTpMwUmaoyf+DzTlE9XCkI1T8s
; etvOBoRBduy4uXXPPXHZCMwFaM5b6Vw/Jnzz1lV54HsLkyo/ytERakBXQm9bHEPNA1DX5cvjLzkDqJ
; EE6dqaVPENrDVbNELhS8UW7OFSTHx5kzJTfkf3cMW2CY6hPXtKWKUp2LfvJ9OpOtfYSAKXmSFiIwnQ
; LvyOriFQ3BqXqbU1OQFdzqkN7zkwsPf8tm0LpopjqL6AU7K7e8FUqo05F5l9FDPULkd8o6eFVRK3sG
; MoJjf3j9mRGPphUmZ0DJXTs17QLzJzbZyKWJmqlPgGDx3FeYhrt3B1hFPjMtQR36nvo8xFb1sfuC4y
; UyhmymcRZW6ZFDPl3VKgpB6kLxIb/eBQZgpc9INKmeH0LBex24fTp8MXmV3FrXLXuHRVHpCsrJ51Ye
; odwRfW/z9HWzp0DxdSkRjKDKdnuYhdPXw6VxM6xUyxcSrMygNSlLnShYkdGRwcPAuJi6pYlHq7kMVs
; dHT0DBgv5Rlr1xa9bRVIvcgMNt69e/clqJ+aauNUwOkMcwsOmxy5frIuTD0zdZW1NQG4q0EVbBv9oA
; Iy9B09WvS2uZCic5W2ccqiRMqcuySlkn6gLTO1K4gqCRvf5xY+QsfQ2bPNmvR1hoTOVdLGFLgiCTll
; qkryYT7vFMXDlYpQMRdfbU0Kit5WBhI611w2diEUSchVW1NJdCTGOyVZWzO2/iHn1Ea9baG28eDoXM
; FWVdnYBDWSIC1Tncn5w+0IeqdiXkiCfqQWc+HSj8cfv+vq+PhN001aGO0EUNdNm36b5Llsl41TwyBc
; va1OmVUqxZQ4wlPpBzegm/ruSJkfffS+7/btu7mcngFAPtdly353NcX51y4bhygzZXGlvLtJmZW5SC
; gUUzL3Twz9kAzoxtAPW16YchHbDdPB0wQbx1BmCmJkqjbKrGwdcVFMSZ2riRD9kEiXaUOIfoToVNHb
; fh++gj0hG6d8FlVh41SE9La+TUi5OmJSTE6Ny5iOmPQjl9dLh4t+UClJ0dvSC/Y01cacdm1pYUOUWf
; keiKu9u7v7c3hIFYmL9I5s3rz5s1zpMm1A+rFx48YvU+hUp+ptYwv2NNnGqdDTwlIos/I9DBbiiRMn
; xo8cOXK2qoFDw+3du/c8yPmqUnUgtm7d+ilIvWAQU+j64sV3dpTellOwB2w8MjIyXrWNe3p6PsEal1
; UlmAOgnI9C15XvISg/qoJqIHTKnOtKjQ3mtTUb/aACqO1s19tKFOzB/K5NtHEs9D5SKg8o8wc2DyT+
; PGfSIoBLsZ9bb+vyMnMKHwFmq9720CGeztWWz5Wbz6ldNg7B5eAJeaqVOTihzNTSSYv0l/ddco29UU
; 4BxcsspbedDY4hvWDPbLWx5DUuSiTB5alW+D+xNS6l6EfMJVeXhysFsV5mbmnvputtbQV7mmJjasYM
; qfLtsZ9+tn+vOAFdDv1wUeaYAUylH6mXXLlazPXr//jNkSO/+rZp1PbIkV9+t2HDHxpp49iDg2vjVP
; ENbkh4wipuQDeFfkgUc0mhmBQ6RR38mA3JpFNNKXyEBXs4NuZ8M6ZQzLrYOLVd3JCUxHdiDP2Q9sBR
; 6Yd0XhgqXXFR5roXPjIvMsc4/4qN+etJSTzIHEAb/ciZuMhHPzh0itKub7KGKHMd9bahi8w+599str
; GLWebK/aMkH6Z3RKcfuXSuJkz6UVX9Q3OyxqZSrItjiHqReZElZWi7bZxbAGNWHpCizC6onB2B2pqA
; KoQJCFwUMEmqCFoj0FMNZQtT6FQ7Cx9BGGTLlluiLzLr9VPbYeODBw/+ox02hrmVM10mQOV6MNa47O
; /vv1hlbU0w0oEDB85xamumGg36CZOlSYWPQOfKKdjTbhvnFLy4bIw1LnOe0irHy5vFXLg3yqkw6VQO
; MYQNJmXmBsqrKnzE0bmaHki0cW55m83Gevn2Km3MKW4VgpJ8mO/jP6feNlT/MKcW0/VsroQxp2MIHD
; xr1sxP6q/PA5m7fqrPxqnFrdppYx+U1GqneKdCHq4UUAO60lpMqgeSe2pLX8QeHLyRpXOl2lhyss52
; G9vGUHE7EuuBlOpIykkopcVMqX9oSx9BBeptL1z4UXISMHDwdHXNbcW2zbExl2KmBO0pxa3qaGMEUm
; bFoZjcGpepFJMTL+Ps6BL1D1O1mDBWu3at/iLlIvbIiGpt2/b7r1IoJtfGqRQT/n1q0L6dNk6trYk2
; xvWgUjqSspO5EEs/pAK6sad2qgbSNXbUHd3chOD03LGD7hjCgj2xEkbJoH2s86/pNo6tPGA7aJTZET
; 2IansIGFW6xiXFw5VCpyiTL0Q/cjmPKF5MH50KXcRGnattsoYoZg5hBoVi5rJxyH62SIJEuxwbq5iO
; SHBoX0dcp7a0BnKhZbLa6EdOiZk5Ec12MS+Mb6eHi9iHD/9Qbxsq2OOjmDk92O20sYti5raxr7amjz
; Ir1wN1ipn75c2OYFtICXJoIG2TRqcfuTSQtnZ1ihlLp9AxBGGV2II9OsXsBBubFLPONla+B4Kxjh8/
; /s7w8PDbufWmZkd6e3s/hqRYMJBVtQuAjICQMAkGscp2wWCvvfbaX1InCoRVUgr2gI0hMdXQ0NBEbg
; GIaeO+vr4Pq7YxtIsJ19pp4xAjUa6/wMzUILeCyVql9Emvf5jq4UoB7mTr1q372kY/cgFPKxjnnIFy
; W7to41yBcheQMmN5jk6xMYwzxTH0f00odz0GJjSZAAAAAElFTkSuQmCC
; thumbnail end

; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.42mm
; support material extrusion width = 0.42mm
; first layer extrusion width = 0.50mm

;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M104 S215 ; set extruder temp
M109 S215 ; wait for extruder temp
G28                                        ; move X/Y/Z to min endstops
G1 Z0.28                                   ; lift nozzle a bit 
G92 E0 
G1 Y3 F2400                                    ; zero the extruded length 
G1 X180  E40 F500                       ; Extrude 25mm of filament in a 5cm line. 
G92 E0                                     ; zero the extruded length again 
G1 E-0.2 F3000                                ; Retract a little 
G1 X181 F4000                              ; Quickly wipe away from the filament line
M117
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
M107
;LAYER_CHANGE
;Z:0.25
;HEIGHT:0.25
G1 E-2.5 F4800
G1 Z.25 F9000
G92 E0
G1 X134.75 Y134.75
G1 E2.5 F4800
G92 E0
M204 S5000
;TYPE:External perimeter
;WIDTH:0.499999
G1 X85.25 Y134.75 E2.2505
G1 X85.25 Y85.25 E4.501
G1 X134.75 Y85.25 E6.7515
G1 X134.75 Y110 E7.87675
G1 X134.75 Y134.69 E8.99927
M204 S20000
;WIPE_START
G1 F7200
G1 X134.75 Y134.75 E8.96127
G1 X130.863 Y134.75 E6.49927
;WIPE_END
G92 E0
G1 X134.39 Y129.198 F9000
G1 E2.5 F4800
M204 S5000
;TYPE:Internal infill
;WIDTH:0.5
G1 X134.39 Y134.39 E2.73605
G1 X133.248 Y134.39 E2.78797
G1 X131.914 Y133.62 E2.858
G1 X131.914 Y130.252 E3.01113
G1 X134.221 Y128.92 E3.13224
G1 X134.221 Y125.551 E3.28541
G1 X131.914 Y124.219 E3.40652
G1 X131.914 Y120.85 E3.55969
G1 X134.221 Y119.519 E3.68078
G1 X134.221 Y116.15 E3.83395
G1 X131.914 Y114.818 E3.95506
G1 X131.914 Y111.449 E4.10823
G1 X134.221 Y110.118 E4.22932
G1 X134.221 Y106.749 E4.38249
G1 X131.914 Y105.417 E4.5036
G1 X131.914 Y102.048 E4.65677
G1 X134.221 Y100.716 E4.77788
G1 X134.221 Y97.348 E4.93101
G1 X131.914 Y96.016 E5.05212
G1 X131.914 Y92.647 E5.20529
G1 X134.221 Y91.315 E5.3264
G1 X134.221 Y87.947 E5.47953
G1 X131.914 Y86.615 E5.60064
G1 X131.914 Y85.61 E5.64633
G1 X131.507 Y85.61 E5.66483
G1 X131.507 Y86.615 E5.71052
G1 X129.201 Y87.947 E5.8316
G1 X129.201 Y91.315 E5.98473
G1 X131.507 Y92.647 E6.10581
G1 X131.507 Y96.016 E6.25898
G1 X129.201 Y97.348 E6.38006
G1 X129.201 Y100.716 E6.53319
G1 X131.507 Y102.048 E6.65427
G1 X131.507 Y105.417 E6.80744
G1 X129.201 Y106.749 E6.92852
G1 X129.201 Y110.118 E7.08169
G1 X131.507 Y111.449 E7.20274
G1 X131.507 Y114.818 E7.35591
G1 X129.201 Y116.15 E7.47699
G1 X129.201 Y119.519 E7.63016
G1 X131.507 Y120.85 E7.75121
G1 X131.507 Y124.219 E7.90438
G1 X129.201 Y125.551 E8.02546
G1 X129.201 Y128.92 E8.17863
G1 X131.507 Y130.252 E8.29971
G1 X131.507 Y133.62 E8.45284
G1 X130.174 Y134.39 E8.52283
G1 X127.82 Y134.39 E8.62985
G1 X126.487 Y133.62 E8.69984
G1 X126.487 Y130.252 E8.85297
G1 X128.793 Y128.92 E8.97405
G1 X128.793 Y125.551 E9.12722
G1 X126.487 Y124.219 E9.2483
G1 X126.487 Y120.85 E9.40147
G1 X128.793 Y119.519 E9.52252
G1 X128.793 Y116.15 E9.67569
G1 X126.487 Y114.818 E9.79677
G1 X126.487 Y111.449 E9.94994
G1 X128.793 Y110.118 E10.07099
G1 X128.793 Y106.749 E10.22416
G1 X126.487 Y105.417 E10.34524
G1 X126.487 Y102.048 E10.49841
G1 X128.793 Y100.716 E10.61949
G1 X128.793 Y97.348 E10.77262
G1 X126.487 Y96.016 E10.8937
G1 X126.487 Y92.647 E11.04687
G1 X128.793 Y91.315 E11.16795
G1 X128.793 Y87.947 E11.32108
G1 X126.487 Y86.615 E11.44216
G1 X126.487 Y85.61 E11.48785
G1 X126.08 Y85.61 E11.50635
G1 X126.08 Y86.615 E11.55204
G1 X123.773 Y87.947 E11.67315
G1 X123.773 Y91.315 E11.82628
G1 X126.08 Y92.647 E11.94739
G1 X126.08 Y96.016 E12.10056
G1 X123.773 Y97.348 E12.22167
G1 X123.773 Y100.716 E12.3748
G1 X126.08 Y102.048 E12.49591
G1 X126.08 Y105.417 E12.64908
G1 X123.773 Y106.749 E12.77019
G1 X123.773 Y110.118 E12.92336
G1 X126.08 Y111.449 E13.04445
G1 X126.08 Y114.818 E13.19762
G1 X123.773 Y116.15 E13.31873
G1 X123.773 Y119.519 E13.4719
G1 X126.08 Y120.85 E13.59299
G1 X126.08 Y124.219 E13.74616
G1 X123.773 Y125.551 E13.86727
G1 X123.773 Y128.92 E14.02044
G1 X126.08 Y130.252 E14.14155
G1 X126.08 Y133.62 E14.29468
G1 X124.746 Y134.39 E14.36471
G1 X122.393 Y134.39 E14.47169
G1 X121.059 Y133.62 E14.54172
G1 X121.059 Y130.252 E14.69485
G1 X123.366 Y128.92 E14.81596
G1 X123.366 Y125.551 E14.96913
G1 X121.059 Y124.219 E15.09024
G1 X121.059 Y120.85 E15.24341
G1 X123.366 Y119.519 E15.3645
G1 X123.366 Y116.15 E15.51767
G1 X121.059 Y114.818 E15.63878
G1 X121.059 Y111.449 E15.79195
G1 X123.366 Y110.118 E15.91304
G1 X123.366 Y106.749 E16.06621
G1 X121.059 Y105.417 E16.18732
G1 X121.059 Y102.048 E16.34049
G1 X123.366 Y100.716 E16.4616
G1 X123.366 Y97.348 E16.61473
G1 X121.059 Y96.016 E16.73584
G1 X121.059 Y92.647 E16.88901
G1 X123.366 Y91.315 E17.01012
G1 X123.366 Y87.947 E17.16325
G1 X121.059 Y86.615 E17.28436
G1 X121.059 Y85.61 E17.33005
G1 X120.652 Y85.61 E17.34855
G1 X120.652 Y86.615 E17.39424
G1 X118.345 Y87.947 E17.51535
G1 X118.345 Y91.315 E17.66848
G1 X120.652 Y92.647 E17.78959
G1 X120.652 Y96.016 E17.94276
G1 X118.345 Y97.348 E18.06387
G1 X118.345 Y100.716 E18.217
G1 X120.652 Y102.048 E18.33811
G1 X120.652 Y105.417 E18.49128
G1 X118.345 Y106.749 E18.61239
G1 X118.345 Y110.118 E18.76556
G1 X120.652 Y111.449 E18.88665
G1 X120.652 Y114.818 E19.03982
G1 X118.345 Y116.15 E19.16093
G1 X118.345 Y119.519 E19.3141
G1 X120.652 Y120.85 E19.43519
G1 X120.652 Y124.219 E19.58836
G1 X118.345 Y125.551 E19.70947
G1 X118.345 Y128.92 E19.86264
G1 X120.652 Y130.252 E19.98375
G1 X120.652 Y133.62 E20.13688
G1 X119.318 Y134.39 E20.20691
G1 X116.965 Y134.39 E20.31389
G1 X115.631 Y133.62 E20.38392
G1 X115.631 Y130.252 E20.53705
G1 X117.938 Y128.92 E20.65816
G1 X117.938 Y125.551 E20.81133
G1 X115.631 Y124.219 E20.93244
G1 X115.631 Y120.85 E21.08561
G1 X117.938 Y119.519 E21.2067
G1 X117.938 Y116.15 E21.35987
G1 X115.631 Y114.818 E21.48098
G1 X115.631 Y111.449 E21.63415
G1 X117.938 Y110.118 E21.75524
G1 X117.938 Y106.749 E21.90841
G1 X115.631 Y105.417 E22.02952
G1 X115.631 Y102.048 E22.18269
G1 X117.938 Y100.716 E22.3038
G1 X117.938 Y97.348 E22.45693
G1 X115.631 Y96.016 E22.57804
G1 X115.631 Y92.647 E22.73121
G1 X117.938 Y91.315 E22.85232
G1 X117.938 Y87.947 E23.00545
G1 X115.631 Y86.615 E23.12656
G1 X115.631 Y85.61 E23.17225
G1 X115.224 Y85.61 E23.19075
G1 X115.224 Y86.615 E23.23644
G1 X112.917 Y87.947 E23.35755
G1 X112.917 Y91.315 E23.51068
G1 X115.224 Y92.647 E23.63179
G1 X115.224 Y96.016 E23.78496
G1 X112.917 Y97.348 E23.90607
G1 X112.917 Y100.716 E24.0592
G1 X115.224 Y102.048 E24.18031
G1 X115.224 Y105.417 E24.33348
G1 X112.917 Y106.749 E24.45459
G1 X112.917 Y110.118 E24.60776
G1 X115.224 Y111.449 E24.72885
G1 X115.224 Y114.818 E24.88202
G1 X112.917 Y116.15 E25.00313
G1 X112.917 Y119.519 E25.1563
G1 X115.224 Y120.85 E25.27739
G1 X115.224 Y124.219 E25.43056
G1 X112.917 Y125.551 E25.55167
G1 X112.917 Y128.92 E25.70484
G1 X115.224 Y130.252 E25.82595
G1 X115.224 Y133.62 E25.97908
G1 X113.89 Y134.39 E26.04911
G1 X111.537 Y134.39 E26.15609
G1 X110.204 Y133.62 E26.22608
G1 X110.204 Y130.252 E26.37921
G1 X112.51 Y128.92 E26.50029
G1 X112.51 Y125.551 E26.65346
G1 X110.204 Y124.219 E26.77454
G1 X110.204 Y120.85 E26.92771
G1 X112.51 Y119.519 E27.04876
G1 X112.51 Y116.15 E27.20193
G1 X110.204 Y114.818 E27.32301
G1 X110.204 Y111.449 E27.47618
G1 X112.51 Y110.118 E27.59723
G1 X112.51 Y106.749 E27.7504
G1 X110.204 Y105.417 E27.87148
G1 X110.204 Y102.048 E28.02465
G1 X112.51 Y100.716 E28.14573
G1 X112.51 Y97.348 E28.29886
G1 X110.204 Y96.016 E28.41994
G1 X110.204 Y92.647 E28.57311
G1 X112.51 Y91.315 E28.69419
G1 X112.51 Y87.947 E28.84732
G1 X110.204 Y86.615 E28.9684
G1 X110.204 Y85.61 E29.01409
G1 X109.796 Y85.61 E29.03264
G1 X109.796 Y86.615 E29.07833
G1 X107.49 Y87.947 E29.19941
G1 X107.49 Y91.315 E29.35254
G1 X109.796 Y92.647 E29.47362
G1 X109.796 Y96.016 E29.62679
G1 X107.49 Y97.348 E29.74787
G1 X107.49 Y100.716 E29.901
G1 X109.796 Y102.048 E30.02208
G1 X109.796 Y105.417 E30.17525
G1 X107.49 Y106.749 E30.29633
G1 X107.49 Y110.118 E30.4495
G1 X109.796 Y111.449 E30.57055
G1 X109.796 Y114.818 E30.72372
G1 X107.49 Y116.15 E30.8448
G1 X107.49 Y119.519 E30.99797
G1 X109.796 Y120.85 E31.11902
G1 X109.796 Y124.219 E31.27219
G1 X107.49 Y125.551 E31.39327
G1 X107.49 Y128.92 E31.54644
G1 X109.796 Y130.252 E31.66752
G1 X109.796 Y133.62 E31.82065
G1 X108.463 Y134.39 E31.89064
G1 X106.11 Y134.39 E31.99762
G1 X104.776 Y133.62 E32.06765
G1 X104.776 Y130.252 E32.22078
G1 X107.083 Y128.92 E32.34189
G1 X107.083 Y125.551 E32.49506
G1 X104.776 Y124.219 E32.61617
G1 X104.776 Y120.85 E32.76934
G1 X107.083 Y119.519 E32.89043
G1 X107.083 Y116.15 E33.0436
G1 X104.776 Y114.818 E33.16471
G1 X104.776 Y111.449 E33.31788
G1 X107.083 Y110.118 E33.43897
G1 X107.083 Y106.749 E33.59214
G1 X104.776 Y105.417 E33.71325
G1 X104.776 Y102.048 E33.86642
G1 X107.083 Y100.716 E33.98753
G1 X107.083 Y97.348 E34.14066
G1 X104.776 Y96.016 E34.26177
G1 X104.776 Y92.647 E34.41494
G1 X107.083 Y91.315 E34.53605
G1 X107.083 Y87.947 E34.68918
G1 X104.776 Y86.615 E34.81029
G1 X104.776 Y85.61 E34.85598
G1 X104.369 Y85.61 E34.87448
G1 X104.369 Y86.615 E34.92017
G1 X102.062 Y87.947 E35.04128
G1 X102.062 Y91.315 E35.19441
G1 X104.369 Y92.647 E35.31552
G1 X104.369 Y96.016 E35.46869
G1 X102.062 Y97.348 E35.5898
G1 X102.062 Y100.716 E35.74293
G1 X104.369 Y102.048 E35.86404
G1 X104.369 Y105.417 E36.01721
G1 X102.062 Y106.749 E36.13832
G1 X102.062 Y110.118 E36.29149
G1 X104.369 Y111.449 E36.41258
G1 X104.369 Y114.818 E36.56575
G1 X102.062 Y116.15 E36.68686
G1 X102.062 Y119.519 E36.84003
G1 X104.369 Y120.85 E36.96112
G1 X104.369 Y124.219 E37.11429
G1 X102.062 Y125.551 E37.2354
G1 X102.062 Y128.92 E37.38857
G1 X104.369 Y130.252 E37.50968
G1 X104.369 Y133.62 E37.66281
G1 X103.035 Y134.39 E37.73284
G1 X100.682 Y134.39 E37.83982
G1 X99.348 Y133.62 E37.90985
G1 X99.348 Y130.252 E38.06298
G1 X101.655 Y128.92 E38.18409
G1 X101.655 Y125.551 E38.33726
G1 X99.348 Y124.219 E38.45837
G1 X99.348 Y120.85 E38.61154
G1 X101.655 Y119.519 E38.73263
G1 X101.655 Y116.15 E38.8858
G1 X99.348 Y114.818 E39.00691
G1 X99.348 Y111.449 E39.16008
G1 X101.655 Y110.118 E39.28117
G1 X101.655 Y106.749 E39.43434
G1 X99.348 Y105.417 E39.55545
G1 X99.348 Y102.048 E39.70862
G1 X101.655 Y100.716 E39.82973
G1 X101.655 Y97.348 E39.98286
G1 X99.348 Y96.016 E40.10397
G1 X99.348 Y92.647 E40.25714
G1 X101.655 Y91.315 E40.37825
G1 X101.655 Y87.947 E40.53138
G1 X99.348 Y86.615 E40.65249
G1 X99.348 Y85.61 E40.69818
G1 X98.941 Y85.61 E40.71668
G1 X98.941 Y86.615 E40.76237
G1 X96.634 Y87.947 E40.88348
G1 X96.634 Y91.315 E41.03661
G1 X98.941 Y92.647 E41.15772
G1 X98.941 Y96.016 E41.31089
G1 X96.634 Y97.348 E41.432
G1 X96.634 Y100.716 E41.58513
G1 X98.941 Y102.048 E41.70624
G1 X98.941 Y105.417 E41.85941
G1 X96.634 Y106.749 E41.98052
G1 X96.634 Y110.118 E42.13369
G1 X98.941 Y111.449 E42.25478
G1 X98.941 Y114.818 E42.40795
G1 X96.634 Y116.15 E42.52906
G1 X96.634 Y119.519 E42.68223
G1 X98.941 Y120.85 E42.80332
G1 X98.941 Y124.219 E42.95649
G1 X96.634 Y125.551 E43.0776
G1 X96.634 Y128.92 E43.23077
G1 X98.941 Y130.252 E43.35188
G1 X98.941 Y133.62 E43.50501
G1 X97.607 Y134.39 E43.57504
G1 X95.254 Y134.39 E43.68202
G1 X93.92 Y133.62 E43.75205
G1 X93.92 Y130.252 E43.90518
G1 X96.227 Y128.92 E44.02629
G1 X96.227 Y125.551 E44.17946
G1 X93.92 Y124.219 E44.30057
G1 X93.92 Y120.85 E44.45374
G1 X96.227 Y119.519 E44.57483
G1 X96.227 Y116.15 E44.728
G1 X93.92 Y114.818 E44.84911
G1 X93.92 Y111.449 E45.00228
G1 X96.227 Y110.118 E45.12337
G1 X96.227 Y106.749 E45.27654
G1 X93.92 Y105.417 E45.39765
G1 X93.92 Y102.048 E45.55082
G1 X96.227 Y100.716 E45.67193
G1 X96.227 Y97.348 E45.82506
G1 X93.92 Y96.016 E45.94617
G1 X93.92 Y92.647 E46.09934
G1 X96.227 Y91.315 E46.22045
G1 X96.227 Y87.947 E46.37358
G1 X93.92 Y86.615 E46.49469
G1 X93.92 Y85.61 E46.54038
G1 X93.513 Y85.61 E46.55888
G1 X93.513 Y86.615 E46.60457
G1 X91.207 Y87.947 E46.72565
G1 X91.207 Y91.315 E46.87878
G1 X93.513 Y92.647 E46.99986
G1 X93.513 Y96.016 E47.15303
G1 X91.207 Y97.348 E47.27411
G1 X91.207 Y100.716 E47.42724
G1 X93.513 Y102.048 E47.54832
G1 X93.513 Y105.417 E47.70149
G1 X91.207 Y106.749 E47.82257
G1 X91.207 Y110.118 E47.97574
G1 X93.513 Y111.449 E48.09679
G1 X93.513 Y114.818 E48.24996
G1 X91.207 Y116.15 E48.37104
G1 X91.207 Y119.519 E48.52421
G1 X93.513 Y120.85 E48.64526
G1 X93.513 Y124.219 E48.79843
G1 X91.207 Y125.551 E48.91951
G1 X91.207 Y128.92 E49.07268
G1 X93.513 Y130.252 E49.19376
G1 X93.513 Y133.62 E49.34689
G1 X92.18 Y134.39 E49.41688
G1 X89.826 Y134.39 E49.5239
G1 X88.493 Y133.62 E49.59389
G1 X88.493 Y130.252 E49.74702
G1 X90.799 Y128.92 E49.8681
G1 X90.799 Y125.551 E50.02127
G1 X88.493 Y124.219 E50.14235
G1 X88.493 Y120.85 E50.29552
G1 X90.799 Y119.519 E50.41657
G1 X90.799 Y116.15 E50.56974
G1 X88.493 Y114.818 E50.69082
G1 X88.493 Y111.449 E50.84399
G1 X90.799 Y110.118 E50.96504
G1 X90.799 Y106.749 E51.11821
G1 X88.493 Y105.417 E51.23929
G1 X88.493 Y102.048 E51.39246
G1 X90.799 Y100.716 E51.51354
G1 X90.799 Y97.348 E51.66667
G1 X88.493 Y96.016 E51.78775
G1 X88.493 Y92.647 E51.94092
G1 X90.799 Y91.315 E52.062
G1 X90.799 Y87.947 E52.21513
G1 X88.493 Y86.615 E52.33621
G1 X88.493 Y85.61 E52.3819
G1 X88.086 Y85.61 E52.4004
G1 X88.086 Y86.615 E52.44609
G1 X85.779 Y87.947 E52.5672
G1 X85.779 Y91.315 E52.72033
G1 X88.086 Y92.647 E52.84144
G1 X88.086 Y96.016 E52.99461
G1 X85.779 Y97.348 E53.11572
G1 X85.779 Y100.716 E53.26885
G1 X88.086 Y102.048 E53.38996
G1 X88.086 Y105.417 E53.54313
G1 X85.779 Y106.749 E53.66424
G1 X85.779 Y110.118 E53.81741
G1 X88.086 Y111.449 E53.9385
G1 X88.086 Y114.818 E54.09167
G1 X85.779 Y116.15 E54.21278
G1 X85.779 Y119.519 E54.36595
G1 X88.086 Y120.85 E54.48704
G1 X88.086 Y124.219 E54.64021
G1 X85.779 Y125.551 E54.76132
G1 X85.779 Y128.92 E54.91449
G1 X88.086 Y130.252 E55.0356
G1 X88.086 Y133.62 E55.18873
G1 X86.752 Y134.39 E55.25876
G1 X85.61 Y134.39 E55.31068
G1 X85.61 Y129.198 E55.54673
M204 S20000
;WIPE_START
G1 F7200;_WIPE
G1 X85.61 Y133.146 E53.04673
;WIPE_END
G92 E0
M107
;TYPE:Custom
G1 Z2.25 F600 ; Move print head up
G1 X5 Y209 F9000 ; present print
G1 Z70.25 F600 ; Move print head further up
G1 Z150 F600 ; Move print head further up
M140 S0 ; turn off heatbed
M104 S0 ; turn off temperature
M107 ; turn off fan
M84; disable motors                    ; disable stepper motors
; objects_info = {"objects":[]}
; filament used [mm] = 101.85
; filament used [cm3] = 0.24
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 59s
; estimated first layer printing time (normal mode) = 59s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = D:\\1111(已去底).png
; bed_shape = 0x0,220x0,220x220,0x220
; bed_temperature = 60
; before_layer_gcode = ; BEFORE_LAYER_CHANGE [layer_num] @ [layer_z]mm
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 5000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1.1
; bridge_speed = 30
; brim_separation = 0.15
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 20000
; default_filament_profile = "Anycubic PLA @MEGA0"
; default_print_profile = 0.20mm NORMAL @MEGA0
; deretract_speed = 80
; disable_fan_first_layers = 2
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = ""
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F600 ; Move print head up{endif}\nG1 X5 Y{print_bed_max[1]*0.95} F{travel_speed*60} ; present print\n{if max_layer_z < max_print_height-10}G1 Z{z_offset+min(max_layer_z+70, max_print_height-10)} F600 ; Move print head further up{endif}\n{if max_layer_z < max_print_height*0.6}G1 Z{max_print_height*0.6} F600 ; Move print head further up{endif}\nM140 S0 ; turn off heatbed\nM104 S0 ; turn off temperature\nM107 ; turn off fan\nM84; disable motors                    ; disable stepper motors
; external_perimeter_acceleration = 5000
; external_perimeter_extrusion_width = 0.42
; external_perimeter_speed = 40%
; external_perimeters_first = 1
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = #FFFF00
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.98
; extrusion_width = 0.42
; fan_always_on = 1
; fan_below_layer_time = 600
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_layer_change = 0
; filament_settings_id = "Anycubic Kobra 2 Pro-PLA"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 90
; fill_density = 15%
; fill_pattern = honeycomb
; first_layer_acceleration = 5000
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.5
; first_layer_height = 0.25
; first_layer_speed = 80
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 200
; gcode_comments = 0
; gcode_flavor = klipper
; gcode_label_objects = disabled
; gcode_resolution = 0.012
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 20000
; infill_anchor = 10
; infill_anchor_max = 10
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 15%
; infill_speed = 60
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 1%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ; AFTER_LAYER_CHANGE [layer_num] @ [layer_z]mm
; layer_height = 0.2
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 20000
; machine_max_acceleration_extruding = 20000
; machine_max_acceleration_retracting = 20000
; machine_max_acceleration_travel = 3000,1250
; machine_max_acceleration_x = 20000
; machine_max_acceleration_y = 20000
; machine_max_acceleration_z = 5000
; machine_max_feedrate_e = 100
; machine_max_feedrate_x = 500
; machine_max_feedrate_y = 500
; machine_max_feedrate_z = 16
; machine_max_jerk_e = 20
; machine_max_jerk_x = 20
; machine_max_jerk_y = 20
; machine_max_jerk_z = 8
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 100
; max_layer_height = 0.28
; max_print_height = 250
; max_print_speed = 300
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 60
; min_feature_size = 25%
; min_layer_height = 0.08
; min_print_speed = 25
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}-{layer_height}-{print_time}-{month}-{day}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 100%
; overhang_speed_1 = 50%
; overhang_speed_2 = 50%
; overhang_speed_3 = 100%
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 10000
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 80
; perimeters = 1
; physical_printer_settings_id = 
; post_process = ArcWelder.exe
; print_settings_id = Anycubic Kobra 2 Pro-PLA
; printer_model = 
; printer_notes = Do not remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_ANYCUBIC\nPRINTER_MODEL_Kobra 2
; printer_settings_id = Anycubic Kobra 2 Pro-PLA
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 2.5
; retract_length_toolchange = 1
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 80
; seam_position = aligned
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 5
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 6
; small_perimeter_speed = 40%
; solid_infill_acceleration = 10000
; solid_infill_below_area = 15
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80%
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM104 S[first_layer_temperature] ; set extruder temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28                                        ; move X/Y/Z to min endstops\nG1 Z0.28                                   ; lift nozzle a bit \nG92 E0 \nG1 Y3 F2400                                    ; zero the extruded length \nG1 X180  E40 F500                       ; Extrude 25mm of filament in a 5cm line. \nG92 E0                                     ; zero the extruded length again \nG1 E-0.2 F3000                                ; Retract a little \nG1 X181 F4000                              ; Quickly wipe away from the filament line\nM117
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 1
; support_material_closing_radius = 2
; support_material_contact_distance = 0.28
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 80
; support_material_style = organic
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 215
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 1
; thumbnails = 230x110/PNG
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.42
; top_solid_infill_acceleration = 5000
; top_solid_infill_speed = 65%
; top_solid_layers = 0
; top_solid_min_thickness = 0.6
; travel_acceleration = 20000
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
